### **1.RESOURCES UTILIZATION ANALYSIS DATASET CLEANING**

Here we will work on the Department dataset to clean and make it ready for the data analysis.

In [1]:
#Needed Libraries will be imported here.
import pandas as pd

In [2]:
#By the file path we are importing the file into the patient_df variable
resource_df=pd.read_csv("C:\\powerbipro\\Health_Domain_pro_Infosys\\MedTrack_DV\\Data\\Raw_data\\resource_utilization_dataset.csv")

In [3]:
#Initially Displaying the top and bottom rows.
resource_df

,resource_utilization_id,date,year,month,quarter,day_of_week,is_weekend,hospital_id,hospital_name,department_id,...,doctors_on_duty_snapshot,overtime_hours,avg_response_time_minutes,cost_per_day_usd,resource_condition,maintenance_due_flag,last_maintenance_date,planned_capacity_next_month,record_source_system,last_updated_timestamp
0,RU00046798,2024-04-26,2024,4,2,Friday,False,H008,Horizon Care Hospital,D15,...,NaN,NaN,NaN,12492.44,Needs Repair,True,2024-04-14,35.0,Analytics-ETL,2024-04-28
1,RU00657417,2025-04-01,2025,4,2,Tuesday,False,H006,Green Valley Hospital,D05,...,3.0,3.8,11.2,3924.07,NaN,False,2024-10-21,16.0,Manual Log,2025-04-02
2,RU00445663,2023-05-12,2023,5,2,Friday,False,H007,Unity Regional Medical Center,D15,...,NaN,NaN,10.7,3879.8,Good,False,2022-12-12,20.0,Analytics-ETL,2023-05-13
3,RU00203003,2022-01-08,2022,1,1,Saturday,True,H002,Lakeview Medical Center,D13,...,NaN,NaN,NaN,5832.61,Functional,True,2021-10-12,27.0,Analytics-ETL,2022-01-11
4,RU00510552,2025-08-06,2025,8,3,Wednesday,False,H006,Green Valley Hospital,D13,...,NaN,NaN,11.1,5502.6,Fair,False,2025-04-24,32.0,Analytics-ETL,2025-08-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838129,RU00004172,2023-10-09,2023,10,4,Monday,False,H005,Metro City Hospital,D15,...,NaN,NaN,NaN,7793.85,Functional,True,2023-07-13,30.0,Analytics-ETL,2023-10-13
838130,RU00144303,2025-01-13,2025,1,1,Monday,False,H008,Horizon Care Hospital,D01,...,NaN,NaN,NaN,9124.45,Functional,True,2024-09-18,24.0,Analytics-ETL,2025-01-14
838131,RU00122681,2021-05-14,2021,5,2,Friday,False,H010,Evercare Medical Center,D14,...,NaN,NaN,NaN,17012.24,Functional,True,2021-02-28,53.0,Analytics-ETL,2021-05-16
838132,RU00390850,2023-12-31,2023,12,4,Sunday,True,H006,Green Valley Hospital,D07,...,NaN,NaN,NaN,877.58,Fair,False,NaN,23.0,Analytics-ETL,2024-01-03
838133,RU00825536,2024-10-21,2024,10,4,Monday,False,H010,Evercare Medical Center,D03,...,NaN,NaN,21.3,1679.7,Good,False,2024-06-24,10.0,Manual Log,2024-10-23

In [4]:
#By the default available functions we are fully displaying the columns ( as per the need we can also display rows as well).
pd.set_option('display.max_columns',33)
resource_df.head(2)

,resource_utilization_id,date,year,month,quarter,day_of_week,is_weekend,hospital_id,hospital_name,department_id,department_name,resource_type,resource_category,total_units_available,units_in_use,units_under_maintenance,utilization_rate_pct,shortage_flag,capacity_hours,utilized_hours,idle_hours,downtime_hours,nurses_on_duty_snapshot,doctors_on_duty_snapshot,overtime_hours,avg_response_time_minutes,cost_per_day_usd,resource_condition,maintenance_due_flag,last_maintenance_date,planned_capacity_next_month,record_source_system,last_updated_timestamp
0,RU00046798,2024-04-26,2024,4,2,Friday,False,H008,Horizon Care Hospital,D15,Urology,Bed,Inpatient Bed,33,28,1.0,84.85,False,792,647.8,120.2,24.0,NaN,NaN,NaN,NaN,12492.44,Needs Repair,True,2024-04-14,35.0,Analytics-ETL,2024-04-28
1,RU00657417,2025-04-01,2025,4,2,Tuesday,False,H006,Green Valley Hospital,D05,Pediatrics,Clinical Staff,Nurses & Doctors,15,13,NaN,86.67,False,120,104.0,16.0,NaN,10.0,3.0,3.8,11.2,3924.07,NaN,False,2024-10-21,16.0,Manual Log,2025-04-02

### **2.SHOW DATASET SHAPE AND SUMMARY BEFORE CLEANING** 

Why we have to make this step ! because by this summary we can noties the changes in the dataset.

In [5]:
#Showing the no.of rows and columns here.
rows,col=resource_df.shape
print("Rows:",rows,"Columns:",col)

Rows: 838134 Columns: 33

In [6]:
#Showing the all columns datatypes for the further usage.
resource_df.dtypes

resource_utilization_id         object
date                            object
year                             int64
month                            int64
quarter                          int64
day_of_week                     object
is_weekend                        bool
hospital_id                     object
hospital_name                   object
department_id                   object
department_name                 object
resource_type                   object
resource_category               object
total_units_available            int64
units_in_use                     int64
units_under_maintenance        float64
utilization_rate_pct           float64
shortage_flag                     bool
capacity_hours                   int64
utilized_hours                 float64
idle_hours                     float64
downtime_hours                 float64
nurses_on_duty_snapshot        float64
doctors_on_duty_snapshot       float64
overtime_hours                 float64
avg_response_time_minutes      float64
cost_per_day_usd                object
resource_condition              object
maintenance_due_flag              bool
last_maintenance_date           object
planned_capacity_next_month    float64
record_source_system            object
last_updated_timestamp          object
dtype: object

In [7]:
#The Statistical information of all the numarical datatpye columns.
resource_df.describe()

,year,month,quarter,total_units_available,units_in_use,units_under_maintenance,utilization_rate_pct,capacity_hours,utilized_hours,idle_hours,downtime_hours,nurses_on_duty_snapshot,doctors_on_duty_snapshot,overtime_hours,avg_response_time_minutes,planned_capacity_next_month
count,838134.000000,838134.000000,838134.000000,838134.000000,838134.000000,558694.000000,825546.000000,838134.000000,838134.000000,838134.000000,558694.000000,279440.000000,279440.000000,279440.000000,530797.000000,821362.000000
mean,2023.000345,6.523341,2.508704,20.386308,14.533701,1.247814,74.218736,429.523107,267.587852,151.718798,18.208389,7.676592,3.285267,1.203797,9.013020,20.899844
std,1.414038,3.448730,1.117086,14.272226,9.754647,1.010070,21.828163,385.736495,253.046828,141.380831,25.988524,3.472443,1.488705,1.202291,4.919787,14.665550
min,2021.000000,1.000000,1.000000,4.000000,1.000000,0.000000,-10.000000,32.000000,14.700000,0.000000,0.000000,1.000000,1.000000,0.000000,0.500000,4.000000
25%,2022.000000,4.000000,2.000000,10.000000,7.000000,0.000000,58.820000,112.000000,88.000000,8.000000,0.120000,5.000000,2.000000,0.300000,5.400000,10.000000
50%,2023.000000,7.000000,3.000000,14.000000,12.000000,1.000000,69.050000,264.000000,128.000000,133.700000,0.560000,8.000000,3.000000,0.800000,8.000000,15.000000
75%,2024.000000,10.000000,4.000000,29.000000,19.000000,2.000000,86.670000,696.000000,436.000000,239.300000,38.415000,10.000000,4.000000,1.700000,12.100000,30.000000
max,2025.000000,12.000000,4.000000,58.000000,81.000000,3.000000,210.000000,1392.000000,1837.000000,820.400000,72.000000,15.000000,6.000000,12.000000,36.600000,63.000000

In [8]:
#It will Describe every column, including numerical and categorical columns and other supported dtypes as well
#So for the categorical values it will return COUNT,UNIQUE,TOP,FREQUENCY.
resource_df.describe(include='all')

,resource_utilization_id,date,year,month,quarter,day_of_week,is_weekend,hospital_id,hospital_name,department_id,department_name,resource_type,resource_category,total_units_available,units_in_use,units_under_maintenance,utilization_rate_pct,shortage_flag,capacity_hours,utilized_hours,idle_hours,downtime_hours,nurses_on_duty_snapshot,doctors_on_duty_snapshot,overtime_hours,avg_response_time_minutes,cost_per_day_usd,resource_condition,maintenance_due_flag,last_maintenance_date,planned_capacity_next_month,record_source_system,last_updated_timestamp
count,838134,838134,838134.000000,838134.000000,838134.000000,838134,838134,838134,838134,838134,838134,838134,838134,838134.000000,838134.000000,558694.000000,825546.000000,838134,838134.000000,838134.000000,838134.000000,558694.000000,279440.000000,279440.000000,279440.000000,530797.000000,812987,536355,838134,787895,821362.000000,838134,838134
unique,828274,1826,NaN,NaN,NaN,7,2,10,10,15,15,12,64,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,435467,24,2,2023,NaN,12,1829
top,RU00134917,2022-07-24,NaN,NaN,NaN,Sunday,False,H002,Lakeview Medical Center,D02,Orthopedics,Clinical Staff,Inpatient Bed,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,392.84,Functional,False,2022-05-08,NaN,Analytics-ETL,2022-02-09
freq,2,471,NaN,NaN,NaN,119843,598476,83865,83865,55921,55921,270544,270492,NaN,NaN,NaN,NaN,660938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1780,194518,614240,493,NaN,406454,526
mean,NaN,NaN,2023.000345,6.523341,2.508704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.386308,14.533701,1.247814,74.218736,NaN,429.523107,267.587852,151.718798,18.208389,7.676592,3.285267,1.203797,9.013020,NaN,NaN,NaN,NaN,20.899844,NaN,NaN
std,NaN,NaN,1.414038,3.448730,1.117086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.272226,9.754647,1.010070,21.828163,NaN,385.736495,253.046828,141.380831,25.988524,3.472443,1.488705,1.202291,4.919787,NaN,NaN,NaN,NaN,14.665550,NaN,NaN
min,NaN,NaN,2021.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,1.000000,0.000000,-10.000000,NaN,32.000000,14.700000,0.000000,0.000000,1.000000,1.000000,0.000000,0.500000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN
25%,NaN,NaN,2022.000000,4.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,7.000000,0.000000,58.820000,NaN,112.000000,88.000000,8.000000,0.120000,5.000000,2.000000,0.300000,5.400000,NaN,NaN,NaN,NaN,10.000000,NaN,NaN
50%,NaN,NaN,2023.000000,7.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,12.000000,1.000000,69.050000,NaN,264.000000,128.000000,133.700000,0.560000,8.000000,3.000000,0.800000,8.000000,NaN,NaN,NaN,NaN,15.000000,NaN,NaN
75%,NaN,NaN,2024.000000,10.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,19.000000,2.000000,86.670000,NaN,696.000000,436.000000,239.300000,38.415000,10.000000,4.000000,1.700000,12.100000,NaN,NaN,NaN,NaN,30.000000,NaN,NaN
max,NaN,NaN,2025.000000,12.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.000000,81.000000,3.000000,210.000000,NaN,1392.000000,1837.000000,820.400000,72.000000,15.000000,6.000000,12.000000,36.600000,NaN,NaN,NaN,NaN,63.000000,NaN,NaN

In [9]:
#Detailed view of Duplicates by the column wise count.
for col in resource_df.columns:
    print(f"\n{col}:")
    print(resource_df[col].duplicated().sum())

resource_utilization_id:
9860

date:
836308

year:
838129

month:
838122

quarter:
838130

day_of_week:
838127

is_weekend:
838132

hospital_id:
838124

hospital_name:
838124

department_id:
838119

department_name:
838119

resource_type:
838122

resource_category:
838070

total_units_available:
838080

units_in_use:
838054

units_under_maintenance:
838129

utilization_rate_pct:
837265

shortage_flag:
838132

capacity_hours:
838068

utilized_hours:
826845

idle_hours:
831431

downtime_hours:
837063

nurses_on_duty_snapshot:
838118

doctors_on_duty_snapshot:
838127

overtime_hours:
838014

avg_response_time_minutes:
837816

cost_per_day_usd:
402666

resource_condition:
838109

maintenance_due_flag:
838132

last_maintenance_date:
836110

planned_capacity_next_month:
838073

record_source_system:
838122

last_updated_timestamp:
836305

In [10]:
#Here we only showing the columns  which have null values not all the columns.
Null_values_cols=resource_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

units_under_maintenance        279440
utilization_rate_pct            12588
downtime_hours                 279440
nurses_on_duty_snapshot        558694
doctors_on_duty_snapshot       558694
overtime_hours                 558694
avg_response_time_minutes      307337
cost_per_day_usd                25147
resource_condition             301779
last_maintenance_date           50239
planned_capacity_next_month     16772
dtype: int64

In [11]:
#Here we finding out how much percentage the null values we have ( miss value percentage % )
missing_values=resource_df.isnull().sum()
miss_pct=(missing_values[missing_values > 0].sum() / resource_df.size )*100
round(miss_pct,2)

10.66

In [12]:
#Here we finding out the over column wise percentage average.
avg_col=(missing_values[missing_values > 0] / len(resource_df)) * 100
print("column wise missing value % avg:",round(avg_col.mean(),2))

column wise missing value % avg: 31.98

In [13]:
#Here we finding out the date converage 
max_date=max(resource_df['date'])
min_date=min(resource_df['date'])
print("The date coverage :",max_date," - ",min_date)

The date coverage : 2025-12-31  -  2021-01-01

### **3.CLEAN UP PROCESS BY DUPLICATE REMOVEL AND NULL VALUE FILLING OR REMOVEL.**

Here we will remove the duplicates first and then we will fill the null values presented columns eaither by statistical values, or we can eliminate themn completely.

#### **-->Work on Duplicates**

In [ ]:
#Before removing duplicate values we cheching why does the duplication happened whether by different columns values under resource_utilization_id or repeated data.
resource_df[resource_df['resource_utilization_id'].duplicated(keep=False)].sort_values('resource_utilization_id') # keep =False will give all the dulicate occurences

In [ ]:
#Removing the dulicate values by the 'resource_utilization_id'.
resource_df.drop_duplicates(subset=['resource_utilization_id'], keep='first',inplace=True) #keep='first' will keep the duplicate of first row remove remaining 
                                                                                           #subset=['resource_utilization_id'] will used to decide the whether a row is duplicate or not.

In [ ]:
#Checking whether the column 'resource_utilization_id' have any duplicate values.
resource_df['resource_utilization_id'].duplicated().sum()

0

#### **-->WORKING ON NULL VALUES**

In [ ]:
def mean_cal(val):

    return resource_df[val].sum() / (resource_df[val].count() - resource_df[val].isna().sum())

In [ ]:
#1.Here we filling the units under maintenance by the original mean (avg) value.
resource_df['units_under_maintenance']=resource_df['units_under_maintenance'].fillna(mean_cal('units_under_maintenance'))

In [ ]:
#2.Here we recalculating the utilization rate pct to eliminate the any NA values , and rounded into 2 decimals.
resource_df['utilization_rate_pct']=round((resource_df['units_in_use'] / resource_df['total_units_available'])*100,2)

In [ ]:
#3.Here we filling downtime hours by the original mean (avg) value.
resource_df['downtime_hours']=resource_df['downtime_hours'].fillna(mean_cal('downtime_hours'))

In [ ]:
#4.Here we filling the nurses on duty snapshot by the original mean (avg) value.
resource_df['nurses_on_duty_snapshot']=resource_df['nurses_on_duty_snapshot'].fillna(mean_cal('nurses_on_duty_snapshot'))

In [ ]:
#5.Here we filling the doctors on duty snapshot by the original mean (avg) value.
resource_df['doctors_on_duty_snapshot']=resource_df['doctors_on_duty_snapshot'].fillna(mean_cal('doctors_on_duty_snapshot'))

In [ ]:
#6.Here we filling the overtime hours by the original mean (avg) value.
resource_df['overtime_hours']=resource_df['overtime_hours'].fillna(mean_cal('overtime_hours'))

In [ ]:
#7.Here we filling the avg response time minutes by the original mean (avg) value.
resource_df['avg_response_time_minutes']=resource_df['avg_response_time_minutes'].fillna(mean_cal('avg_response_time_minutes'))

In [ ]:
resource_df['cost_per_day_usd'].unique()

array(['12492.44', '3924.07', '3879.8', ..., '7793.85', '9124.45',
       '17012.24'], dtype=object)

In [ ]:
#8.Here we filling the cost per day usd by the original mean (avg) value.
resource_df['cost_per_day_usd']=(
resource_df['cost_per_day_usd']
.str.replace('$','',regex='False')
.str.replace(',','',regex='False')
.str.lstrip('$')
.str.replace('USD','',regex='False')
.astype(float)
)
resource_df['cost_per_day_usd']=resource_df['cost_per_day_usd'].fillna(mean_cal('cost_per_day_usd'))

In [ ]:
#9.Here we fill the NA of resource condition based on the frequent item.
resource_df['resource_condition']=resource_df['resource_condition'].fillna('Functional')

In [ ]:
#10.Here we fill the NA of last maintenance based on the min() item.
resource_df['last_maintenance_date']=resource_df['last_maintenance_date'].astype('date32[pyarrow]')
resource_df['last_maintenance_date']=resource_df['last_maintenance_date'].fillna(resource_df['last_maintenance_date'].min())

In [ ]:
#11. Here we are filling the planned capacity next month by the mean(avg)
resource_df['planned_capacity_next_month']=resource_df['planned_capacity_next_month'].fillna(mean_cal('planned_capacity_next_month'))

#### **--> Checking does there exist NAN values**

In [ ]:
#Here we only showing the columns  which have null values not all the columns.
Null_values_cols=resource_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

Series([], dtype: int64)

### **4.CORRECTION : COL_NAMES, COL_VALUES , DTYPES ETC.**

#### **-->Standardize ID's**

In [ ]:
#Here we capitalizing the all the first letter of the column names.
resource_df.columns = resource_df.columns.str.capitalize()
resource_df.columns

Index(['Resource_utilization_id', 'Date', 'Year', 'Month', 'Quarter',
       'Day_of_week', 'Is_weekend', 'Hospital_id', 'Hospital_name',
       'Department_id', 'Department_name', 'Resource_type',
       'Resource_category', 'Total_units_available', 'Units_in_use',
       'Units_under_maintenance', 'Utilization_rate_pct', 'Shortage_flag',
       'Capacity_hours', 'Utilized_hours', 'Idle_hours', 'Downtime_hours',
       'Nurses_on_duty_snapshot', 'Doctors_on_duty_snapshot', 'Overtime_hours',
       'Avg_response_time_minutes', 'Cost_per_day_usd', 'Resource_condition',
       'Maintenance_due_flag', 'Last_maintenance_date',
       'Planned_capacity_next_month', 'Record_source_system',
       'Last_updated_timestamp'],
      dtype='object')

In [ ]:
#Here we Change the numarical ID's into the Strings.
cols=resource_df.columns
for ids in cols:
    if ids.endswith('id'):
        resource_df[ids]=resource_df[ids].astype('string')

#### **-->Standardize Departments**

In [ ]:
#Here we assigning the values to the department according to the department ids.
Dept_id_mapping={
    'D01':'Cardiology',
    'D02':'Orthopedics',
    'D03':'Neurology',
    'D04':'Oncology',
    'D05':'Pediatrics',
    'D06':'General surgery',
    'D07':'Emergency',
    'D08':'Obstetrics & gynecology',
    'D09':'Nephrology',
    'D10':'Pulmonology',
    'D11':'Gastroenterology',
    'D12':'Psychiatry',
    'D13':'Icu',
    'D14':'General medicine',
    'D15':'Urology'    
}

resource_df['Department_name']=resource_df['Department_id'].map(Dept_id_mapping)

#### **-->Date standardization**

In [ ]:
#Here we are changing the int dtype of the column date into the date dtype
resource_df['Date']=pd.to_datetime(resource_df['Date'])
resource_df['Last_maintenance_date']=pd.to_datetime(resource_df['Last_maintenance_date']) # here last maintenance date as well.
resource_df['Last_updated_timestamp']=pd.to_datetime(resource_df['Last_updated_timestamp']) # here last updated timestamp date as well.

#### **--> Standardize Text**

In [ ]:
#Here we are performing removing the leading and trailing spaces from the values in the columns.
column_names=['Resource_type',
              'Resource_category',
              'Resource_condition',
              'Record_source_system'
                                ]

for col in column_names:
    resource_df[col]=resource_df[col].str.strip()

In [ ]:
#Here we are performing the capitalize to remove any deplicate values.
column_names_cap=['Hospital_name',
                  'Resource_type',
                  'Resource_category',
                  'Resource_condition',
                  'Record_source_system'
                                ]

for col in column_names_cap:
    resource_df[col]=resource_df[col].str.capitalize()

In [ ]:
#Here we are rounding the floating values into 2 decimals.
column_names_float=['Units_under_maintenance',
                    'Downtime_hours',
                    'Nurses_on_duty_snapshot',
                    'Doctors_on_duty_snapshot',
                    'Overtime_hours',
                    'Avg_response_time_minutes'
                    ]

for col in column_names_float:
    resource_df[col]=round(resource_df[col],2)

#### **-->Outlier validation**

In [ ]:
resource_df.describe(include='all')

,Resource_utilization_id,Date,Year,Month,Quarter,Day_of_week,Is_weekend,Hospital_id,Hospital_name,Department_id,Department_name,Resource_type,Resource_category,Total_units_available,Units_in_use,Units_under_maintenance,Utilization_rate_pct,Shortage_flag,Capacity_hours,Utilized_hours,Idle_hours,Downtime_hours,Nurses_on_duty_snapshot,Doctors_on_duty_snapshot,Overtime_hours,Avg_response_time_minutes,Cost_per_day_usd,Resource_condition,Maintenance_due_flag,Last_maintenance_date,Planned_capacity_next_month,Record_source_system,Last_updated_timestamp
count,828274,828274,828274.000000,828274.000000,828274.000000,828274,828274,828274,828274,828274,828274,828274,828274,828274.000000,828274.000000,828274.000000,828274.000000,828274,828274.000000,828274.000000,828274.000000,828274.000000,828274.000000,828274.000000,828274.000000,828274.000000,828274.000000,828274,828274,828274,828274.000000,828274,828274
unique,828274,NaN,NaN,NaN,NaN,7,2,10,10,15,15,3,16,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2,NaN,NaN,3,NaN
top,RU00046798,NaN,NaN,NaN,NaN,Saturday,False,H010,Evercare medical center,D01,Cardiology,Bed,Inpatient bed,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Functional,False,NaN,NaN,Analytics-etl,NaN
freq,1,NaN,NaN,NaN,NaN,118423,591439,82855,82855,55246,55246,276133,276133,NaN,NaN,NaN,NaN,653199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,496761,606926,NaN,NaN,415078,NaN
mean,NaN,2023-07-02 11:40:17.087098624,2023.000493,6.523795,2.508845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.388345,14.534815,1.665459,74.192640,NaN,429.577864,267.616887,151.735493,24.292658,-2.560529,-1.098148,-0.398665,13.559159,5917.725137,NaN,NaN,2023-01-22 20:55:25.056201472,20.910772,NaN,2023-07-04 23:39:11.369715968
min,NaN,2021-01-01 00:00:00,2021.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,1.000000,0.000000,25.000000,NaN,32.000000,14.700000,0.000000,0.000000,-7.680000,-3.290000,-1.200000,0.500000,-250.000000,NaN,NaN,2020-06-16 00:00:00,4.000000,NaN,2021-01-02 00:00:00
25%,NaN,2022-04-02 00:00:00,2022.000000,4.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,7.000000,1.000000,58.820000,NaN,112.000000,88.000000,8.000000,0.280000,-7.680000,-3.290000,-1.200000,6.900000,1757.700000,NaN,NaN,2021-09-27 00:00:00,10.000000,NaN,2022-04-04 00:00:00
50%,NaN,2023-07-03 00:00:00,2023.000000,7.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,12.000000,2.000000,69.050000,NaN,288.000000,128.000000,133.700000,36.440000,-7.680000,-3.290000,-1.200000,13.000000,4030.715000,NaN,NaN,2023-01-25 00:00:00,15.000000,NaN,2023-07-05 00:00:00
75%,NaN,2024-10-01 00:00:00,2024.000000,10.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,19.000000,2.500000,86.670000,NaN,696.000000,436.100000,239.300000,36.440000,5.000000,2.000000,0.300000,21.410000,7079.997500,NaN,NaN,2024-05-24 00:00:00,29.000000,NaN,2024-10-04 00:00:00
max,NaN,2025-12-31 00:00:00,2025.000000,12.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.000000,81.000000,3.000000,175.000000,NaN,1392.000000,1837.000000,820.400000,72.000000,15.000000,6.000000,12.000000,36.600000,999999.990000,NaN,NaN,2025-12-29 00:00:00,63.000000,NaN,2026-01-04 00:00:00
std,NaN,NaN,1.414081,3.448821,1.117108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.272633,9.754146,1.014178,21.431014,NaN,385.747792,253.037013,141.393694,22.896439,7.512150,3.216522,1.328944,7.142657,25991.790558,NaN,NaN,NaN,14.518511,NaN,NaN

In [ ]:
#Here we find out the some columns have the negative values in it so by using the abs we changed them as positive once.
resource_df['Nurses_on_duty_snapshot']=abs(resource_df['Nurses_on_duty_snapshot'])
resource_df['Doctors_on_duty_snapshot']=abs(resource_df['Doctors_on_duty_snapshot'])
resource_df['Overtime_hours']=abs(resource_df['Overtime_hours'])
resource_df['Cost_per_day_usd']=abs(resource_df['Cost_per_day_usd'])

In [ ]:
#Here once again we showing the all the dtypes of the columns.
resource_df.dtypes

Resource_utilization_id        string[python]
Date                           datetime64[ns]
Year                                    int64
Month                                   int64
Quarter                                 int64
Day_of_week                            object
Is_weekend                               bool
Hospital_id                    string[python]
Hospital_name                          object
Department_id                  string[python]
Department_name                        object
Resource_type                          object
Resource_category                      object
Total_units_available                   int64
Units_in_use                            int64
Units_under_maintenance               float64
Utilization_rate_pct                  float64
Shortage_flag                            bool
Capacity_hours                          int64
Utilized_hours                        float64
Idle_hours                            float64
Downtime_hours                        float64
Nurses_on_duty_snapshot               float64
Doctors_on_duty_snapshot              float64
Overtime_hours                        float64
Avg_response_time_minutes             float64
Cost_per_day_usd                      float64
Resource_condition                     object
Maintenance_due_flag                     bool
Last_maintenance_date          datetime64[ns]
Planned_capacity_next_month           float64
Record_source_system                   object
Last_updated_timestamp         datetime64[ns]
dtype: object

In [ ]:
resource_df.head(2)

,Resource_utilization_id,Date,Year,Month,Quarter,Day_of_week,Is_weekend,Hospital_id,Hospital_name,Department_id,Department_name,Resource_type,Resource_category,Total_units_available,Units_in_use,Units_under_maintenance,Utilization_rate_pct,Shortage_flag,Capacity_hours,Utilized_hours,Idle_hours,Downtime_hours,Nurses_on_duty_snapshot,Doctors_on_duty_snapshot,Overtime_hours,Avg_response_time_minutes,Cost_per_day_usd,Resource_condition,Maintenance_due_flag,Last_maintenance_date,Planned_capacity_next_month,Record_source_system,Last_updated_timestamp
0,RU00046798,2024-04-26,2024,4,2,Friday,False,H008,Horizon care hospital,D15,Urology,Bed,Inpatient bed,33,28,1.0,84.85,False,792,647.8,120.2,24.00,7.68,3.29,1.2,21.41,12492.44,Needs repair,True,2024-04-14,35.0,Analytics-etl,2024-04-28
1,RU00657417,2025-04-01,2025,4,2,Tuesday,False,H006,Green valley hospital,D05,Pediatrics,Clinical staff,Nurses & doctors,15,13,2.5,86.67,False,120,104.0,16.0,36.44,10.00,3.00,3.8,11.20,3924.07,Functional,False,2024-10-21,16.0,Manual log,2025-04-02

#### **-->For docu finding NUMBERS COLS**

In [ ]:
#Here we finding out the int and float related columns by specifying 'number' parameter.
numeric_columns = resource_df.select_dtypes(  #Here the select dtypes is pandas fun which can return the specified dtype columns
    include='number'
).columns.tolist() # here we get the pandas dataframe so we converting that into python list.

for col in numeric_columns:
    print(col)

Year
Month
Quarter
Total_units_available
Units_in_use
Units_under_maintenance
Utilization_rate_pct
Capacity_hours
Utilized_hours
Idle_hours
Downtime_hours
Nurses_on_duty_snapshot
Doctors_on_duty_snapshot
Overtime_hours
Avg_response_time_minutes
Cost_per_day_usd
Planned_capacity_next_month

In [ ]:
#Here we are removing the extra date rows that are more then the hospital admissions dates.
resource_df = resource_df[resource_df['Date'] <= '2025-12-30']

In [ ]:
resource_df['Date'].max()

Timestamp('2025-12-30 00:00:00')

### **5.CONVERTING THE CURRENT DATAFRAME INTO THE CSV FILE**

As per the requriement we are going to make this dataframe into the csv gile for the analysisi.

In [ ]:
#Here we converted the current department_df into csv file.
resource_df.to_csv(
    r"C:\powerbipro\Health_Domain_pro_Infosys\MedTrack_DV\Data\Processed_data\Resources_cleaned.csv",
    index=False
)

### **6.SUMMARY OF THE DATASET**


1. **Dataset Overview**
   We first provide an overview of the dataset, including its structure, number of rows and columns, and the key information available in the dataset.

2. **Pre-Cleaning Data Summary**
   Next, we analyze the dataset **before cleaning** by performing statistical analysis and examining the data **column-wise** to identify missing values, duplicates, data types, inconsistent values, and other data-quality issues.

3. **Data Cleaning**
   The dataset is then cleaned by **removing duplicate records** and handling missing values. Numerical columns are filled using the **mean value**, while missing values in categorical columns are replaced with the **most frequently occurring value (mode)**.

4. **Column and Data-Type Standardization**
   After that, we standardize the dataset by **correcting column names**, removing **repeated/multi-value entries**, and converting columns to their appropriate **data types** to ensure consistency and improve data usability.

5. **Final Dataset Export**
   Finally, the cleaned and standardized dataset is converted and exported into **CSV format**, making it ready for further analysis, visualization, and dashboard development.