### **1.HOSPITAL OVERVIEW DATASET CLEANING**   

Here we are importing the dataset by the using the pandas libray and then we cleaned up it to get the analysis ready data set for the tableau.

In [1]:
#Needed Libraries will be imported here.
import pandas as pd

In [2]:
#By the file path we are importing the file into the hospital_df variable
hospital_df=pd.read_csv("C:\\powerbipro\\Health_Domain_pro_Infosys\\MedTrack_DV\\Data\\Raw_data\\hospital_overview_dataset.csv")

In [3]:
#Initially Displaying the top and bottom rows.
hospital_df

,admission_id,patient_id,hospital_id,hospital_name,department_id,department_name,admission_date,discharge_date,admission_type,admission_source,...,age_group,admission_year,admission_month,admission_quarter,day_of_week,is_weekend_admission,previous_admission_id,readmission_flag,readmission_within_30_days,last_updated_timestamp
0,A0285311,P005912,H007,Unity Regional Medical Center,D13,I.C.U.,2021-01-25,2021-01-30,Elective,ER Walk-in,...,Child (2-12),2021,1,1,Monday,False,NaN,0,0,2021-02-15
1,A0336483,P022400,H007,Unity Regional Medical Center,D15,urology,2021-08-23,2021-08-28,Elective,Ambulance,...,Elderly (65+),2021,8,3,Monday,False,NaN,0,0,2021-09-29
2,A0079148,P099712,H003,Riverside Community Hospital,D06,General Surgery,2021-02-16,2021-02-19,Emergency,Transfer from another facility,...,Elderly (65+),2021,2,1,Tuesday,False,A0106110,1,1,2021-04-29
3,A0131277,P159044,H010,Evercare Medical Center,D01,Cardiology,2022-07-03,2022-07-05,Elective,Self,...,Senior (51-65),2022,7,3,Sunday,True,A0140202,1,0,2022-07-05
4,A0048190,P221415,H003,Riverside Community Hospital,D10,Respiratory Medicine,2022-01-25,2022-02-04,Transfer,Self,...,Infant (0-1),2022,1,1,Tuesday,False,NaN,0,0,2022-04-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358745,A0324221,P100145,H002,Lakeview Medical Center,D05,peds,2023-02-07,2023-02-12,Transfer,ER Walk-in,...,Elderly (65+),2023,2,1,Tuesday,False,A0247138,1,0,2023-02-23
358746,A0003459,P193483,H009,Pinecrest General Hospital,D08,OBGYN,2021-01-15,NaN,Urgent,Self,...,Elderly (65+),2021,1,1,Friday,False,NaN,0,0,2021-02-13
358747,A0119250,P016686,H001,St. Mary General Hospital,D15,urology,2025-02-21,2025-03-01,Transfer,Physician Referral,...,Senior (51-65),2025,2,1,Friday,False,A0245098,1,0,2025-04-02
358748,A0050445,P069841,H001,St. Mary General Hospital,D02,ORTHO,2025-01-26,2025-02-03,Transfer,Referral,...,Middle Age (36-50),2025,1,1,Sunday,True,A0231274,1,0,2025-02-14
358749,A0046499,P193489,H003,Riverside Community Hospital,D06,GEN SURGERY,2025-05-01,2025-05-04,Transfer,Transfer from another facility,...,Middle Age (36-50),2025,5,2,Thursday,False,A0192345,1,0,2025-05-12

In [4]:
#By the default available functions we are fully displaying the columns ( as per the need we can also display rows as well).
pd.set_option('display.max_columns',38)
hospital_df.head(2)

,admission_id,patient_id,hospital_id,hospital_name,department_id,department_name,admission_date,discharge_date,admission_type,admission_source,bed_id,bed_type,room_number,length_of_stay_days,patient_age,patient_gender,attending_doctor_id,attending_doctor_name,diagnosis_code,diagnosis_description,primary_procedure_code,insurance_type,total_bill_amount,payment_status,discharge_status,patient_satisfaction_score,mortality_flag,record_source_system,age_group,admission_year,admission_month,admission_quarter,day_of_week,is_weekend_admission,previous_admission_id,readmission_flag,readmission_within_30_days,last_updated_timestamp
0,A0285311,P005912,H007,Unity Regional Medical Center,D13,I.C.U.,2021-01-25,2021-01-30,Elective,ER Walk-in,B1416,General Ward,484.0,5.0,3.0,Other,DOC0147,Dr. Aisha Johnson,K80,Gallstones,PRC-5428,Private Insurance,5571.74,Insurance Claim Processing,Discharged,5.0,0,EHR-Main,Child (2-12),2021,1,1,Monday,False,NaN,0,0,2021-02-15
1,A0336483,P022400,H007,Unity Regional Medical Center,D15,urology,2021-08-23,2021-08-28,Elective,Ambulance,B0464,General Ward,636.0,5.0,94.0,m,DOC0170,Dr. Sofia Khan,O80,Normal Delivery,PRC-5227,Uninsured,4693.32,Overdue,Discharged,4.0,0,EHR-Main,Elderly (65+),2021,8,3,Monday,False,NaN,0,0,2021-09-29

### **2.SHOW DATASET SHAPE AND SUMMARY BEFORE CLEANING** 

Why we have to make this step ! because by this summary we can noties the changes in the dataset.

In [5]:
#Showing the no.of rows and columns here.
rows,col=hospital_df.shape
print("Rows:",rows,"Columns:",col)

Rows: 358750 Columns: 38

In [6]:
#Showing the all columns datatypes for the further usage.
hospital_df.dtypes

admission_id                   object
patient_id                     object
hospital_id                    object
hospital_name                  object
department_id                  object
department_name                object
admission_date                 object
discharge_date                 object
admission_type                 object
admission_source               object
bed_id                         object
bed_type                       object
room_number                   float64
length_of_stay_days           float64
patient_age                   float64
patient_gender                 object
attending_doctor_id            object
attending_doctor_name          object
diagnosis_code                 object
diagnosis_description          object
primary_procedure_code         object
insurance_type                 object
total_bill_amount              object
payment_status                 object
discharge_status               object
patient_satisfaction_score    float64
mortality_flag                  int64
record_source_system           object
age_group                      object
admission_year                  int64
admission_month                 int64
admission_quarter               int64
day_of_week                    object
is_weekend_admission             bool
previous_admission_id          object
readmission_flag                int64
readmission_within_30_days      int64
last_updated_timestamp         object
dtype: object

In [7]:
#The Statistical information of all the numarical datatpye columns.
hospital_df.describe()

,room_number,length_of_stay_days,patient_age,patient_satisfaction_score,mortality_flag,admission_year,admission_month,admission_quarter,readmission_flag,readmission_within_30_days
count,347958.000000,355888.000000,346263.000000,294163.000000,358750.000000,358750.000000,358750.000000,358750.000000,358750.00000,358750.000000
mean,524.353376,5.439959,47.809674,3.305769,0.029550,2022.997541,6.519147,2.507339,0.48618,0.025151
std,245.320446,29.744969,28.841219,1.854309,0.169342,1.414487,3.448891,1.118016,0.49981,0.156584
min,100.000000,-2.000000,-3.000000,1.000000,0.000000,2021.000000,1.000000,1.000000,0.00000,0.000000
25%,312.000000,2.000000,23.000000,2.000000,0.000000,2022.000000,4.000000,2.000000,0.00000,0.000000
50%,524.000000,4.000000,47.000000,3.000000,0.000000,2023.000000,7.000000,3.000000,0.00000,0.000000
75%,737.000000,6.000000,72.000000,4.000000,0.000000,2024.000000,10.000000,4.000000,1.00000,0.000000
max,949.000000,999.000000,250.000000,10.000000,1.000000,2025.000000,12.000000,4.000000,1.00000,1.000000

In [8]:
#It will Describe every column, including numerical and categorical columns and other supported dtypes as well
#So for the categorical values it will return COUNT,UNIQUE,TOP,FREQUENCY.
hospital_df.describe(include='all')

,admission_id,patient_id,hospital_id,hospital_name,department_id,department_name,admission_date,discharge_date,admission_type,admission_source,bed_id,bed_type,room_number,length_of_stay_days,patient_age,patient_gender,attending_doctor_id,attending_doctor_name,diagnosis_code,diagnosis_description,primary_procedure_code,insurance_type,total_bill_amount,payment_status,discharge_status,patient_satisfaction_score,mortality_flag,record_source_system,age_group,admission_year,admission_month,admission_quarter,day_of_week,is_weekend_admission,previous_admission_id,readmission_flag,readmission_within_30_days,last_updated_timestamp
count,358750,358750,358750,358750,358750,358750,358750,356608,358750,358750,358750,358750,347958.000000,355888.000000,346263.000000,351578,358750,353345,358750,351585,358750,351779,344408,350012,355248,294163.000000,358750.000000,358750,358750,358750.000000,358750.000000,358750.000000,358750,358750,174417,358750.00000,358750.000000,358750
unique,353500,179814,10,40,15,75,1825,1844,7,24,2000,5,NaN,NaN,NaN,10,300,400,15,15,8999,26,299328,22,22,NaN,NaN,4,7,NaN,NaN,NaN,7,2,170186,NaN,NaN,1913
top,A0204390,P207872,H007,Unity Regional Medical Center,D09,NEPHRO,2024-07-05,2024-10-02,Emergency,Self,B1929,General Ward,NaN,NaN,NaN,M,DOC0279,Dr. Daniel Brown,F32,Major Depressive Disorder,PRC-8958,Medicare/Medicaid,50.0,Partially Paid,Discharged,NaN,NaN,EHR-Main,Elderly (65+),NaN,NaN,NaN,Friday,False,A0190856,NaN,NaN,2022-02-15
freq,2,10,36361,34963,24229,5044,253,253,100805,57703,224,161494,NaN,NaN,NaN,35445,1307,968,24366,23851,67,56595,511,67546,279297,NaN,NaN,179258,112239,NaN,NaN,NaN,51711,256195,3,NaN,NaN,247
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,524.353376,5.439959,47.809674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.305769,0.029550,NaN,NaN,2022.997541,6.519147,2.507339,NaN,NaN,NaN,0.48618,0.025151,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245.320446,29.744969,28.841219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.854309,0.169342,NaN,NaN,1.414487,3.448891,1.118016,NaN,NaN,NaN,0.49981,0.156584,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,-2.000000,-3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,NaN,2021.000000,1.000000,1.000000,NaN,NaN,NaN,0.00000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,312.000000,2.000000,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,0.000000,NaN,NaN,2022.000000,4.000000,2.000000,NaN,NaN,NaN,0.00000,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,524.000000,4.000000,47.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,0.000000,NaN,NaN,2023.000000,7.000000,3.000000,NaN,NaN,NaN,0.00000,0.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,737.000000,6.000000,72.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,0.000000,NaN,NaN,2024.000000,10.000000,4.000000,NaN,NaN,NaN,1.00000,0.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,949.000000,999.000000,250.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,1.000000,NaN,NaN,2025.000000,12.000000,4.000000,NaN,NaN,NaN,1.00000,1.000000,NaN

In [9]:
#Find out the Duplicate values before NULL because sometime if primary column have the Duplicate values by removing them,
#we can reduce the null values count.
hospital_df.duplicated().sum()

5250

In [10]:
#Detailed view of Duplicates by the column wise count.
for col in hospital_df.columns:
    print(f"\n{col}:")
    print(hospital_df[col].duplicated().sum())

admission_id:
5250

patient_id:
178936

hospital_id:
358740

hospital_name:
358710

department_id:
358735

department_name:
358675

admission_date:
356925

discharge_date:
356905

admission_type:
358743

admission_source:
358726

bed_id:
356750

bed_type:
358745

room_number:
357899

length_of_stay_days:
358710

patient_age:
358648

patient_gender:
358739

attending_doctor_id:
358450

attending_doctor_name:
358349

diagnosis_code:
358735

diagnosis_description:
358734

primary_procedure_code:
349751

insurance_type:
358723

total_bill_amount:
59421

payment_status:
358727

discharge_status:
358727

patient_satisfaction_score:
358739

mortality_flag:
358748

record_source_system:
358746

age_group:
358743

admission_year:
358745

admission_month:
358738

admission_quarter:
358746

day_of_week:
358743

is_weekend_admission:
358748

previous_admission_id:
188563

readmission_flag:
358748

readmission_within_30_days:
358748

last_updated_timestamp:
356837

In [11]:
#Here we only showing the columns  which have null values not all the columns.
Null_values_cols=hospital_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

discharge_date                  2142
room_number                    10792
length_of_stay_days             2862
patient_age                    12487
patient_gender                  7172
attending_doctor_name           5405
diagnosis_description           7165
insurance_type                  6971
total_bill_amount              14342
payment_status                  8738
discharge_status                3502
patient_satisfaction_score     64587
previous_admission_id         184333
dtype: int64

In [12]:
#Here we finding out how much percentage the null values we have ( miss value percentage % )
missing_values=hospital_df.isnull().sum()
miss_pct=(missing_values[missing_values > 0].sum() / hospital_df.size ) * 100
print("cell wise miss value %:",round(miss_pct,2))

cell wise miss value %: 2.42

In [13]:
#Here we finding out the over column wise percentage average.
avg_col=(missing_values[missing_values > 0] / len(hospital_df)) * 100
print("column wise missing value % avg:",round(avg_col.mean(),2))

column wise missing value % avg: 7.09

In [14]:
#Here we finding out the date converage in this dataset.
max_date=max(hospital_df['admission_date'])
min_date=min(hospital_df['admission_date'])
print("The date coverage :",max_date," - ",min_date)

The date coverage : 2025-12-30  -  2021-01-01

### **3.CLEAN UP PROCESS BY DUPLICATE REMOVEL AND NULL VALUE FILLING OR REMOVEL.**

Here we will remove the duplicates first and then we will fill the null values presented columns eaither by statistical values, or we can eliminate themn completely.

#### -->**Work on Duplicates**

In [15]:
#Before removing duplicate values we cheching why does the duplication happened whether by different columns values under admission id or repeated data.
hospital_df[hospital_df['admission_id'].duplicated(keep=False)].sort_values('admission_id') # keep =False will give all the dulicate occurences

,admission_id,patient_id,hospital_id,hospital_name,department_id,department_name,admission_date,discharge_date,admission_type,admission_source,bed_id,bed_type,room_number,length_of_stay_days,patient_age,patient_gender,attending_doctor_id,attending_doctor_name,diagnosis_code,diagnosis_description,primary_procedure_code,insurance_type,total_bill_amount,payment_status,discharge_status,patient_satisfaction_score,mortality_flag,record_source_system,age_group,admission_year,admission_month,admission_quarter,day_of_week,is_weekend_admission,previous_admission_id,readmission_flag,readmission_within_30_days,last_updated_timestamp
190146,A0000098,P156974,H008,Horizon Care Hospital,D02,Orthopedic,2021-01-31,2021-02-02,Emergency,TRANSFER FROM ANOTHER FACILITY,B1316,General Ward,839.0,2.0,4.0,Female,DOC0177,Dr. James Müller,K80,Gallstones,PRC-3486,Medicare/Medicaid,2429.82,Pending,Discharged,1.0,0,Third-Party Feed,Child (2-12),2021,1,1,Sunday,True,NaN,0,0,2021-03-29
157900,A0000098,P156974,H008,Horizon Care Hospital,D02,Orthopedic,2021-01-31,2021-02-02,Emergency,TRANSFER FROM ANOTHER FACILITY,B1316,General Ward,839.0,2.0,4.0,Female,DOC0177,Dr. James Müller,K80,Gallstones,PRC-3486,Medicare/Medicaid,2429.82,Pending,Discharged,1.0,0,Third-Party Feed,Child (2-12),2021,1,1,Sunday,True,NaN,0,0,2021-03-29
52953,A0000211,P060063,H001,ST. MARY GENERAL HOSPITAL,D11,Gastro,2025-12-12,2025-12-14,Urgent,ER Walk-in,B1393,Private Room,543.0,2.0,74.0,F,DOC0026,Dr. Mei Silva,K80,Gallstones,PRC-6817,Private Insurance,"$4,460.39",Insurance Claim Processing,Discharged,2.0,0,EHR-Legacy,Elderly (65+),2025,12,4,Friday,False,NaN,0,0,2026-01-30
307056,A0000211,P060063,H001,ST. MARY GENERAL HOSPITAL,D11,Gastro,2025-12-12,2025-12-14,Urgent,ER Walk-in,B1393,Private Room,543.0,2.0,74.0,F,DOC0026,Dr. Mei Silva,K80,Gallstones,PRC-6817,Private Insurance,"$4,460.39",Insurance Claim Processing,Discharged,2.0,0,EHR-Legacy,Elderly (65+),2025,12,4,Friday,False,NaN,0,0,2026-01-30
160687,A0000249,P180984,H001,St. Mary General Hospital,D03,Neurology,2024-02-28,2024-03-01,Transfer,ER Walk-in,B0269,General Ward,463.0,2.0,17.0,m,DOC0126,Dr. Daniel Silva,K80,Gallstones,PRC-9895,Corporate,3349.91,Overdue,LAMA (Left Against Medical Advice),2.0,0,EHR-Legacy,Teen (13-18),2024,2,1,Wednesday,False,A0103412,1,0,2024-04-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286944,A0349694,P078097,H004,Sunrise Health Institute,D12,PSYCH,2023-06-09,2023-06-12,Urgent,Transfer from another facility,B1995,Private Room,354.0,3.0,76.0,male,DOC0220,Dr. Emma Ahmed,K35,Acute Appendicitis,PRC-6268,Self-Pay,4356.48,Insurance Claim Processing,Discharged,NaN,0,EHR-Main,Elderly (65+),2023,6,2,Friday,False,NaN,0,0,2023-08-17
229717,A0349787,P055297,H002,Lakeview Medical Center,D12,psychiatry,2024-12-23,2024-12-25,Elective,Physician Referral,B1337,General Ward,942.0,2.0,20.0,F,DOC0214,Dr. Yusuf Smith,E11,Type 2 Diabetes Mellitus,PRC-1542,Self-Pay,2795.47,Overdue,Discharged,4.0,0,EHR-Legacy,Adult (19-35),2024,12,4,Monday,False,A0063370,1,0,2025-02-12
174259,A0349787,P055297,H002,Lakeview Medical Center,D12,psychiatry,2024-12-23,2024-12-25,Elective,Physician Referral,B1337,General Ward,942.0,2.0,20.0,F,DOC0214,Dr. Yusuf Smith,E11,Type 2 Diabetes Mellitus,PRC-1542,Self-Pay,2795.47,Overdue,Discharged,4.0,0,EHR-Legacy,Adult (19-35),2024,12,4,Monday,False,A0063370,1,0,2025-02-12
170641,A0349881,P032939,H010,Evercare Medical Center,D10,Pulmonology,2024-02-11,2024-02-13,Elective,Self,B0187,Semi-Private,462.0,2.0,31.0,m,DOC0066,Dr. Chloe Park,N39,Urinary Tract Infection,PRC-7741,Government Scheme,3355.23,Overdue,Discharged,4.0,0,EHR-Main,Adult (19-35),2024,2,1,Sunday,True,NaN,0,0,2024-04-07
126053,A0349881,P032939,H010,Evercare Medical Center,D10,Pulmonology,2024-02-11,2024-02-13,Elective,Self,B0187,Semi-Private,462.0,2.0,31.0,m,DOC0066,Dr. Chloe Park,N39,Urinary Tract Infection,PRC-7741,Government Scheme,3355.23,Overdue,Discharged,4.0,0,EHR-Main,Adult (19-35),2024,2,1,Sunday,True,NaN,0,0,2024-04-07

In [16]:
#Removing the dulicate values by the admission_id and the returned dataframe will be stored in hospital_df.
hospital_df.drop_duplicates(subset=['admission_id'], keep='first',inplace=True)  #keep='first' will keep the duplicate of first row remove remaining 
                                                                                        #subset=['admission_id'] will used to decide the whether a row is duplicate or not.

In [17]:
#Checking whether the new hospital_df column admission_id have any duplicate values.
hospital_df['admission_id'].duplicated().sum()

0

#### **--> WORK ON NULL VALUES**

In [18]:
#1.discharge_date NA values replace with frequent one.
hospital_df['discharge_date']=hospital_df['discharge_date'].fillna(hospital_df['discharge_date'].mode()[0])

In [19]:
#2.Room_number Na values replace with frequent one as well and also changed the dtype into int64
hospital_df['room_number']=hospital_df['room_number'].fillna( hospital_df['room_number'].mode()[0])
hospital_df['room_number']=hospital_df['room_number'].astype('int64')

In [20]:
#3.Length of stay days  Na values will be replaced with the mean values of that column.
hospital_df['length_of_stay_days']=hospital_df['length_of_stay_days'].fillna(5.0)
hospital_df['length_of_stay_days']=hospital_df['length_of_stay_days'].astype('int64')

In [21]:
#4.patient age Na valules will be replaced by the mean value.
hospital_df['patient_age']=hospital_df['patient_age'].fillna(47)
hospital_df['patient_age']=hospital_df['patient_age'].astype('int64')

In [22]:
#5.patient gender Na values will be replaced with the others
hospital_df['patient_gender']=hospital_df['patient_gender'].fillna('Others')
hospital_df['patient_gender']=hospital_df['patient_gender'].astype('string')

In [23]:
gender_mapping = {
    'M': 'Male',
    'm': 'Male',
    'male': 'Male',
    'Male': 'Male',
    
    'F': 'Female',
    'f': 'Female',
    'female': 'Female',
    'Female': 'Female',
    
    'O': 'Others',
    'Other': 'Others'
}

hospital_df['patient_gender'] = (
    hospital_df['patient_gender']
    .replace(gender_mapping)
)

In [24]:
hospital_df['patient_gender'].unique()

<StringArray>
['Others', 'Male', 'Female']
Length: 3, dtype: string

In [25]:
#6.Attending doctor name replaced with the frequent appeared doctor.
hospital_df['attending_doctor_name']=hospital_df['attending_doctor_name'].fillna('Dr. Daniel Brown')

In [26]:
#7.Diagnosis description is marked as Not available for now.
hospital_df['diagnosis_description']=hospital_df['diagnosis_description'].fillna('NOT AVAILABLE')

In [27]:
#8.Insurance type Na will be replaced with the frequent value.
hospital_df['insurance_type']=hospital_df['insurance_type'].fillna('Medicare/Medicaid')

In [28]:
#Here the Insureance have multiple names under the same type.
insurance_mapping = {
    'MEDICARE/MEDICAID':'Medicare',
    '  Medicare/Medicaid  ':'Medicare',
    'medicare/medicaid':'Medicare',
    'Medicare/Medicaid':'Medicare'

}

hospital_df['insurance_type'] = (
    hospital_df['insurance_type']
    .replace(insurance_mapping)
)

In [29]:
#9.Total bill amount values will replaced with the mean and also removel of the doller as well.
#In this column also have doller amount so instead of converting we removed the doller
hospital_df['total_bill_amount'] = pd.to_numeric(
    hospital_df['total_bill_amount']
    .str.replace('$', '', regex=False), # here we are say to the replace method its a normal text not the pattern of a regex
    errors='coerce'  #here we are tell if any invaild data to be encounter make it as null don't push error.
)

hospital_df['total_bill_amount']=hospital_df['total_bill_amount'].fillna(8144.22)

In [30]:
#10.IN payment status column we replacing the nan values with frequently appeared value also removed leading and trail spaces by strip.
hospital_df['payment_status'] = (
    hospital_df['payment_status'].str.strip()
)

In [31]:
payment_status_mapping = {
'NAN':'Partially Paid'
}

hospital_df['payment_status'] = (
    hospital_df['payment_status']
    .replace(payment_status_mapping)
)

hospital_df['payment_status']=hospital_df['payment_status'].fillna('payment_status')  #Here we filling the nan value with frequently used one.

In [32]:
#11.By using mapping we replaced the Na values with the frequently repeated value.
discharge_mapping = {
'nan':'Discharged',
'NAN':'Discharged',
'  nan  ':'Discharged'
}

hospital_df['discharge_status'] = (
    hospital_df['discharge_status']
    .replace(discharge_mapping)
)

hospital_df['discharge_status']=hospital_df['discharge_status'].fillna('Discharged')

In [33]:
#12.patient sattisfaction_score Na will be replaced with the mean.
hospital_df['patient_satisfaction_score']=hospital_df['patient_satisfaction_score'].fillna(hospital_df['patient_satisfaction_score'].mean())

In [34]:
#13 previous admission id will be filled with the not available .
hospital_df['previous_admission_id']=hospital_df['previous_admission_id'].fillna('NOT AVAILABLE')

#### **--> Checking does there exist NAN values**

In [35]:
Null_values_cols=hospital_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

Series([], dtype: int64)

### **4.CORRECTION : COL_NAMES, COL_VALUES , DTYPES ETC.**

In [36]:
#Here we capitalizing the all the first letter of the column names.
hospital_df.columns = hospital_df.columns.str.capitalize()
hospital_df.columns

Index(['Admission_id', 'Patient_id', 'Hospital_id', 'Hospital_name',
       'Department_id', 'Department_name', 'Admission_date', 'Discharge_date',
       'Admission_type', 'Admission_source', 'Bed_id', 'Bed_type',
       'Room_number', 'Length_of_stay_days', 'Patient_age', 'Patient_gender',
       'Attending_doctor_id', 'Attending_doctor_name', 'Diagnosis_code',
       'Diagnosis_description', 'Primary_procedure_code', 'Insurance_type',
       'Total_bill_amount', 'Payment_status', 'Discharge_status',
       'Patient_satisfaction_score', 'Mortality_flag', 'Record_source_system',
       'Age_group', 'Admission_year', 'Admission_month', 'Admission_quarter',
       'Day_of_week', 'Is_weekend_admission', 'Previous_admission_id',
       'Readmission_flag', 'Readmission_within_30_days',
       'Last_updated_timestamp'],
      dtype='object')

#### **--> Standardization Deapartment names**

In [37]:
#Here we assigning the values to the department according to the department ids.
Dept_id_mapping={
    'D01':'Cardiology',
    'D02':'Orthopedics',
    'D03':'Neurology',
    'D04':'Oncology',
    'D05':'Pediatrics',
    'D06':'General surgery',
    'D07':'Emergency',
    'D08':'Obstetrics & gynecology',
    'D09':'Nephrology',
    'D10':'Pulmonology',
    'D11':'Gastroenterology',
    'D12':'Psychiatry',
    'D13':'Icu',
    'D14':'General medicine',
    'D15':'Urology'    
}

hospital_df['Department_name']=hospital_df['Department_id'].map(Dept_id_mapping)

In [38]:
hospital_df['Department_name'].unique() # here we are showing the results.

array(['Icu', 'Urology', 'General surgery', 'Cardiology', 'Pulmonology',
       'Obstetrics & gynecology', 'Gastroenterology', 'Orthopedics',
       'Nephrology', 'Neurology', 'General medicine', 'Emergency',
       'Oncology', 'Pediatrics', 'Psychiatry'], dtype=object)

#### **Diagnosis_description assignment**

In [39]:
#Here we finding out dianosis code unique values by the group by function.
hospital_df.groupby('Diagnosis_code')['Diagnosis_description'].unique().reset_index()

   Diagnosis_code                          Diagnosis_description
0             A41                        [Sepsis, NOT AVAILABLE]
1             C50  [Malignant Neoplasm of Breast, NOT AVAILABLE]
2             E11      [Type 2 Diabetes Mellitus, NOT AVAILABLE]
3             F32     [Major Depressive Disorder, NOT AVAILABLE]
4             I10        [Essential Hypertension, NOT AVAILABLE]
5             I21   [Acute Myocardial Infarction, NOT AVAILABLE]
6             I63  [Cerebral Infarction (Stroke), NOT AVAILABLE]
7             J18                     [Pneumonia, NOT AVAILABLE]
8             J45                        [Asthma, NOT AVAILABLE]
9             K35            [Acute Appendicitis, NOT AVAILABLE]
10            K80                    [Gallstones, NOT AVAILABLE]
11            N18        [Chronic Kidney Disease, NOT AVAILABLE]
12            N39       [Urinary Tract Infection, NOT AVAILABLE]
13            O80               [Normal Delivery, NOT AVAILABLE]
14            S72             [Fracture of Femur, NOT AVAILABLE]

In [40]:
#here we findout the diagnosis have not available values to we find out resprective values for diagnosis id's and map to there respective id's by map.
diagnosis_mapping = {
    'A41': 'Sepsis',
    'C50': 'Malignant Neoplasm of Breast',
    'E11': 'Type 2 Diabetes Mellitus',
    'F32': 'Major Depressive Disorder',
    'I10': 'Essential Hypertension',
    'I21': 'Acute Myocardial Infarction',
    'I63': 'Cerebral Infarction (Stroke)',
    'J18': 'Pneumonia',
    'J45': 'Asthma',
    'K35': 'Acute Appendicitis',
    'K80': 'Gallstones',
    'N18': 'Chronic Kidney Disease',
    'N39': 'Urinary Tract Infection',
    'O80': 'Normal Delivery',
    'S72': 'Fracture of Femur'
}

hospital_df['Diagnosis_description']=hospital_df['Diagnosis_code'].map(diagnosis_mapping)

#### **Removing Attending doctors duplicate values**

In [41]:
#here we are standardizing the doctor names along side of the doctors id's
doc_uq_ids=hospital_df['Attending_doctor_id'].unique()

doc_uq_names=hospital_df['Attending_doctor_name'].unique()
doc_uq_names=sorted(doc_uq_names)
doc_uq_names=doc_uq_names[:300]

d={'docid':doc_uq_ids,'docname':doc_uq_names}
df=pd.DataFrame(data=d)

hospital_df['Attending_doctor_name'] = hospital_df['Attending_doctor_id'].map(
    df.set_index('docid')['docname']  # set_index will crate a dictionary type values so the map will assign accordingly .
)

#### **-->Standardize ID's**

In [42]:
#Here we Change the numarical ID's into the Strings.
hospital_df[['Admission_id','Patient_id','Hospital_id','Department_id']]=hospital_df[['Admission_id','Patient_id','Hospital_id','Department_id']].astype('string')

#### **--> Standardize Text**

In [43]:
#Here we removing the leading and trail spaces from the values on the columns
hospital_df['Hospital_name']=hospital_df['Hospital_name'].str.strip()
hospital_df['Admission_source']=hospital_df['Admission_source'].str.strip()
hospital_df['Insurance_type']=hospital_df['Insurance_type'].str.strip()
hospital_df['Payment_status']=hospital_df['Payment_status'].str.strip()
hospital_df['Discharge_status']=hospital_df['Discharge_status'].str.strip()

In [44]:
#Here we capitalizing the first letter of the category columns
hospital_df['Hospital_name']=hospital_df['Hospital_name'].str.capitalize()
hospital_df['Admission_type']=hospital_df['Admission_type'].str.capitalize()
hospital_df['Admission_source']=hospital_df['Admission_source'].str.capitalize()
hospital_df['Insurance_type']=hospital_df['Insurance_type'].str.capitalize()
hospital_df['Payment_status']=hospital_df['Payment_status'].str.capitalize()
hospital_df['Discharge_status']=hospital_df['Discharge_status'].str.capitalize()

#### **-->Date standardization**

In [45]:
#here if there are any columns which related date containing different formats we making them as the date related dtype columns
dates_related_cols=["Admission_date","Discharge_date","Last_updated_timestamp"]
for col in dates_related_cols:
    hospital_df[col]=pd.to_datetime(hospital_df[col])

In [46]:
#columns Dtypes
hospital_df.dtypes

Admission_id                  string[python]
Patient_id                    string[python]
Hospital_id                   string[python]
Hospital_name                         object
Department_id                 string[python]
Department_name                       object
Admission_date                datetime64[ns]
Discharge_date                datetime64[ns]
Admission_type                        object
Admission_source                      object
Bed_id                                object
Bed_type                              object
Room_number                            int64
Length_of_stay_days                    int64
Patient_age                            int64
Patient_gender                string[python]
Attending_doctor_id                   object
Attending_doctor_name                 object
Diagnosis_code                        object
Diagnosis_description                 object
Primary_procedure_code                object
Insurance_type                        object
Total_bill_amount                    float64
Payment_status                        object
Discharge_status                      object
Patient_satisfaction_score           float64
Mortality_flag                         int64
Record_source_system                  object
Age_group                             object
Admission_year                         int64
Admission_month                        int64
Admission_quarter                      int64
Day_of_week                           object
Is_weekend_admission                    bool
Previous_admission_id                 object
Readmission_flag                       int64
Readmission_within_30_days             int64
Last_updated_timestamp        datetime64[ns]
dtype: object

#### **-->Know NUMBER Related columns**

In [47]:
#Here we finding out the int and float related columns by specifying 'number' parameter.
numeric_columns = hospital_df.select_dtypes(  #Here the select dtypes is pandas fun which can return the specified dtype columns
    include='number'
).columns.tolist() # here we get the pandas dataframe so we converting that into python list.

for col in numeric_columns:
    print(col)

Room_number
Length_of_stay_days
Patient_age
Total_bill_amount
Patient_satisfaction_score
Mortality_flag
Admission_year
Admission_month
Admission_quarter
Readmission_flag
Readmission_within_30_days

#### **-->Outlier Validation**

In [48]:
#Here we checking the column outliers by this describe(include='all')
pd.set_option('display.max_columns',38)
hospital_df.describe(include='all')

,Admission_id,Patient_id,Hospital_id,Hospital_name,Department_id,Department_name,Admission_date,Discharge_date,Admission_type,Admission_source,Bed_id,Bed_type,Room_number,Length_of_stay_days,Patient_age,Patient_gender,Attending_doctor_id,Attending_doctor_name,Diagnosis_code,Diagnosis_description,Primary_procedure_code,Insurance_type,Total_bill_amount,Payment_status,Discharge_status,Patient_satisfaction_score,Mortality_flag,Record_source_system,Age_group,Admission_year,Admission_month,Admission_quarter,Day_of_week,Is_weekend_admission,Previous_admission_id,Readmission_flag,Readmission_within_30_days,Last_updated_timestamp
count,353500,353500,353500,353500,353500,353500,353500,353500,353500,353500,353500,353500,353500.000000,353500.000000,353500.000000,353500,353500,353500,353500,353500,353500,353500,353500.000000,353500,353500,353500.000000,353500.000000,353500,353500,353500.000000,353500.000000,353500.000000,353500,353500,353500,353500.000000,353500.000000,353500
unique,353500,179814,10,10,15,15,NaN,NaN,4,6,2000,5,NaN,NaN,NaN,3,300,300,15,15,8999,7,NaN,7,5,NaN,NaN,4,7,NaN,NaN,NaN,7,2,170187,NaN,NaN,NaN
top,A0285311,P131663,H007,Unity regional medical center,D09,Nephrology,NaN,NaN,Emergency,Referral,B1929,General Ward,NaN,NaN,NaN,Male,DOC0279,Dr. Ivan Ahmed,F32,Major Depressive Disorder,PRC-8958,Medicare,NaN,Partially paid,Discharged,NaN,NaN,EHR-Main,Elderly (65+),NaN,NaN,NaN,Friday,False,NOT AVAILABLE,NaN,NaN,NaN
freq,1,9,35848,35848,23859,23859,NaN,NaN,117009,59178,220,159085,NaN,NaN,NaN,138767,1292,1292,24007,24007,65,65021,NaN,69437,290346,NaN,NaN,176572,110671,NaN,NaN,NaN,50921,252425,181591,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-01 07:14:34.957850624,2023-07-08 08:13:51.656011520,NaN,NaN,NaN,NaN,524.016257,5.434741,47.782724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8144.228417,NaN,NaN,3.305446,0.029581,NaN,NaN,2022.997641,6.519556,2.507403,NaN,NaN,NaN,0.486306,0.025140,2023-08-15 09:42:39.859688960
min,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-01 00:00:00,2021-01-01 00:00:00,NaN,NaN,NaN,NaN,100.000000,-2.000000,-3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-150.000000,NaN,NaN,1.000000,0.000000,NaN,NaN,2021.000000,1.000000,1.000000,NaN,NaN,NaN,0.000000,0.000000,2021-01-02 00:00:00
25%,NaN,NaN,NaN,NaN,NaN,NaN,2022-03-31 00:00:00,2022-04-07 00:00:00,NaN,NaN,NaN,NaN,318.000000,2.000000,24.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3636.940000,NaN,NaN,2.000000,0.000000,NaN,NaN,2022.000000,4.000000,2.000000,NaN,NaN,NaN,0.000000,0.000000,2022-05-15 00:00:00
50%,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-02 00:00:00,2023-07-12 00:00:00,NaN,NaN,NaN,NaN,511.000000,4.000000,47.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6310.870000,NaN,NaN,3.305446,0.000000,NaN,NaN,2023.000000,7.000000,3.000000,NaN,NaN,NaN,0.000000,0.000000,2023-08-16 00:00:00
75%,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-29 00:00:00,2024-10-02 00:00:00,NaN,NaN,NaN,NaN,730.000000,6.000000,71.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8933.462500,NaN,NaN,4.000000,0.000000,NaN,NaN,2024.000000,10.000000,4.000000,NaN,NaN,NaN,1.000000,0.000000,2024-11-13 00:00:00
max,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-30 00:00:00,2026-01-19 00:00:00,NaN,NaN,NaN,NaN,949.000000,999.000000,250.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,999999.990000,NaN,NaN,10.000000,1.000000,NaN,NaN,2025.000000,12.000000,4.000000,NaN,NaN,NaN,1.000000,1.000000,2026-03-29 00:00:00
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,241.631524,29.578045,28.334748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31529.271595,NaN,NaN,1.678794,0.169430,NaN,NaN,1.414452,3.449119,1.118100,NaN,NaN,NaN,0.499813,0.156551,NaN

In [49]:
#Here length of stay days column have some outlier which only 400, 999 so we explicitily replacing them with mean value.
hospital_df['Length_of_stay_days'] = (
    hospital_df['Length_of_stay_days']
    .replace([400, 999], 5.0)
)

#Here some values in Length of stay days in negative values so by using abs we changing them into positive
hospital_df['Length_of_stay_days']=abs(hospital_df['Length_of_stay_days'])

In [50]:
#Here length of stay days column have some outlier which only 0,150,250,199 so we explicitily replacing them with mean value.
hospital_df['Patient_age'] = (
    hospital_df['Patient_age']
    .replace([150,250,199], 47)
)

#Here some values in Length of stay days in negative values so by using abs we changing them into positive
hospital_df['Patient_age']=abs(hospital_df['Patient_age'])

In [51]:
#Here we are making the negative total bill amount into postive and also fixing the decimal points to the 2.
hospital_df['Total_bill_amount']=round(abs(hospital_df['Total_bill_amount']),2)

### **5.CONVERTING THE CURRENT DATAFRAME INTO THE CSV FILE**

As per the requriement we are going to make this dataframe into the csv gile for the analysisi.

In [52]:
#Here we converted the current hospital_df into csv file.
hospital_df.to_csv(
    r"C:\powerbipro\Health_Domain_pro_Infosys\MedTrack_DV\Data\Processed_data\Hospital_cleaned.csv",
    index=False
)

### **6.SUMMARY OF THE DATASET**


1. **Dataset Overview**
   We first provide an overview of the dataset, including its structure, number of rows and columns, and the key information available in the dataset.

2. **Pre-Cleaning Data Summary**
   Next, we analyze the dataset **before cleaning** by performing statistical analysis and examining the data **column-wise** to identify missing values, duplicates, data types, inconsistent values, and other data-quality issues.

3. **Data Cleaning**
   The dataset is then cleaned by **removing duplicate records** and handling missing values. Numerical columns are filled using the **mean value**, while missing values in categorical columns are replaced with the **most frequently occurring value (mode)**.

4. **Column and Data-Type Standardization**
   After that, we standardize the dataset by **correcting column names**, removing **repeated/multi-value entries**, and converting columns to their appropriate **data types** to ensure consistency and improve data usability.

5. **Final Dataset Export**
   Finally, the cleaned and standardized dataset is converted and exported into **CSV format**, making it ready for further analysis, visualization, and dashboard development.