### **1.DEPARTMENT ANALYSIS DATASET CLEANING**

Here we will work on the Department dataset to clean and make it ready for the data analysis.

In [90]:
#Needed Libraries will be imported here.
import pandas as pd

In [91]:
#By the file path we are importing the file into the patient_df variable
department_df=pd.read_csv("C:\\powerbipro\\Health_Domain_pro_Infosys\\MedTrack_DV\\Data\\Raw_data\\department_analytics_dataset.csv")

In [92]:
#Initially Displaying the top and bottom rows.
department_df

,dept_analytics_id,date,year,month,quarter,day_of_week,is_weekend,hospital_id,hospital_name,department_id,department_name,department_type,floor_number,is_24x7,established_year,department_head_name,total_beds,occupied_beds_count,bed_occupancy_rate_pct,target_occupancy_rate_pct,patients_admitted_count,patients_discharged_count,readmission_count,readmission_rate_pct,target_readmission_rate_pct,mortality_count,mortality_rate_pct,avg_length_of_stay_days,target_avg_los_days,avg_treatment_time_hours,transfer_events_count,bed_turnaround_time_hours,nurses_on_duty,doctors_on_duty,base_nurses_per_shift,base_doctors_per_shift,staff_to_patient_ratio,equipment_downtime_hours,avg_patient_age,avg_satisfaction_score,total_billing_usd,avg_cost_per_patient_usd,monthly_budget_allocated_usd,department_efficiency_score,record_source_system,last_updated_timestamp
0,DA00116235,2024-04-11,2024,4,2,Thursday,False,H005,Metro City Hospital,D04,Oncology,Non-Surgical,4,False,2001,Dr. Carlos Ivanov,46,36,78.26,86.677579,2.0,4.0,2.0,100.00,11.565964,0.0,0.0,4.500000,3.872404,58.760000,4.0,0.78,5,3,7,4,0.14,0.14,49.5,2.0,4131.26,2065.63,175431.270786,0.0,Analytics-ETL,2024-04-12
1,DA00092491,2024-04-05,2024,4,2,Friday,False,H004,Sunrise Health Institute,D06,General Surg,Surgical,4,False,2007,Dr. Elena Brown,30,22,73.33,84.645939,1.0,1.0,0.0,0.00,9.408348,0.0,0.0,5.000000,5.685672,49.200000,4.0,3.23,5,5,3,5,0.23,0.16,19.0,5.0,6515.81,6515.81,94570.586818,60.7,Analytics-ETL,2024-04-06
2,DA00097464,2022-11-17,2022,11,4,Thursday,False,H004,Sunrise Health Institute,D09,Nephrology,Non-Surgical,4,False,2000,Dr. Ivan Rossi,51,35,68.63,82.744380,3.0,1.0,2.0,66.67,7.677362,0.0,0.0,6.666667,6.170943,79.023333,4.0,1.47,3,6,3,5,0.09,0.49,38.5,6.0,30686.79,10228.93,231074.980295,0.0,Analytics-ETL,2022-11-19
3,DA00225118,2022-06-04,2022,6,2,Saturday,True,H009,Pinecrest General Hospital,D04,Onco,Non-Surgical,3,False,2015,Dr. Liam Ivanov,29,17,58.62,81.224346,1.0,2.0,0.0,0.00,12.560279,0.0,0.0,9.000000,5.670490,NaN,3.0,0.20,5,4,7,4,0.29,0.36,8.0,3.0,18952.22,18952.22,378377.474788,42.3,Analytics-ETL,2022-06-08
4,DA00054680,2025-09-22,2025,9,3,Monday,False,H002,Lakeview Medical Center,D15,Urology Dept,SURGICAL,2,True,2005,Dr. Nadia Chen,42,28,66.67,71.100059,2.0,1.0,2.0,100.00,8.715063,0.0,0.0,7.500000,5.801750,119.762000,6.0,1.10,4,4,6,5,0.14,0.14,37.0,1.0,22770.44,11385.22,221023.349922,0.0,Manual Aggregation,2025-09-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279373,DA00174204,2023-01-04,2023,1,1,Wednesday,False,H007,Unity Regional Medical Center,D06,General Surgery,Surgical,1,True,2016,Dr. Priya Kowalski,55,44,80.00,87.709910,2.0,2.0,1.0,50.00,8.478073,0.0,0.0,3.000000,5.870792,63.372500,5.0,3.84,2,3,4,4,0.05,0.35,38.0,3.5,12728.47,6364.24,212429.797251,18.1,BI-Warehouse,2023-01-06
279374,DA00170019,2021-07-20,2021,7,3,Tuesday,False,H007,Unity Regional Medical Center,D04,oncology,Non-Surgical,8,False,2012,Dr. Omar Ali,32,21,65.62,84.042755,2.0,1.0,1.0,50.00,9.663452,0.0,0.0,4.500000,5.742029,62.300000,3.0,3.97,8,2,10,3,0.38,0.03,17.5,3.5,8259.49,4129.74,461308.227448,17.6,BI-WAREHOUSE,2021-07-23
279375,DA00031920,2023-05-28,2023,5,2,Sunday,True,H002,Lakeview Medical Center,D03,neuro,Non-Surgical,8,False,2002,Dr. Daniel Costa,25,17,68.00,72.535092,1.0,2.0,0.0,0.00,6.052274,0.0,0.0,2.000000,5.620752,31.135000,4.0,4.85,2,3,5,2,0.12,0.19,40.0,3.0,4908.43,4908.43,458449.991147,61.5,Analytics-ETL,2023-05-29
279376,DA00019987,2025-09-23,2025,9,3,Tuesday,False,H001,St. Mary General Hospital,D11,gastroenterology,Non-Surgical,3,False,2004,Dr. Wei Ahmed,26,16,61.54,71.810099,1.0,2.0,1.0,100.00,7.748165,0.0,0.0,6.000000,3.618071,76.635000,5.0,3.36,8,4,10,5,0.50,0.19,7.0,NaN,6746.45,6746.45,155027.185192,0.0,Analytics-ETL,2025-09-26
279377,DA00028260,2023-05-20,2023,5,2,Saturday,True,H002,Lakeview Medical Center,D01,CARDIOLOGY,Non-Surgical,8,True,2009,Dr. Ivan Silva,53,36,67.92,77.045269,0.0,2.0,0.0,NaN,10.737980,0.0,NaN,NaN,3.021356,3.160000,4.0,1.27,4,1,6,1,0.11,0.78,NaN,NaN,NaN,NaN,109602.166041,74.0,Analytics-ETL,2023-05-23

In [93]:
#By the default available functions we are fully displaying the columns ( as per the need we can also display rows as well).
pd.set_option('display.max_columns',46)
department_df.head(2)

,dept_analytics_id,date,year,month,quarter,day_of_week,is_weekend,hospital_id,hospital_name,department_id,department_name,department_type,floor_number,is_24x7,established_year,department_head_name,total_beds,occupied_beds_count,bed_occupancy_rate_pct,target_occupancy_rate_pct,patients_admitted_count,patients_discharged_count,readmission_count,readmission_rate_pct,target_readmission_rate_pct,mortality_count,mortality_rate_pct,avg_length_of_stay_days,target_avg_los_days,avg_treatment_time_hours,transfer_events_count,bed_turnaround_time_hours,nurses_on_duty,doctors_on_duty,base_nurses_per_shift,base_doctors_per_shift,staff_to_patient_ratio,equipment_downtime_hours,avg_patient_age,avg_satisfaction_score,total_billing_usd,avg_cost_per_patient_usd,monthly_budget_allocated_usd,department_efficiency_score,record_source_system,last_updated_timestamp
0,DA00116235,2024-04-11,2024,4,2,Thursday,False,H005,Metro City Hospital,D04,Oncology,Non-Surgical,4,False,2001,Dr. Carlos Ivanov,46,36,78.26,86.677579,2.0,4.0,2.0,100.0,11.565964,0.0,0.0,4.5,3.872404,58.76,4.0,0.78,5,3,7,4,0.14,0.14,49.5,2.0,4131.26,2065.63,175431.270786,0.0,Analytics-ETL,2024-04-12
1,DA00092491,2024-04-05,2024,4,2,Friday,False,H004,Sunrise Health Institute,D06,General Surg,Surgical,4,False,2007,Dr. Elena Brown,30,22,73.33,84.645939,1.0,1.0,0.0,0.0,9.408348,0.0,0.0,5.0,5.685672,49.20,4.0,3.23,5,5,3,5,0.23,0.16,19.0,5.0,6515.81,6515.81,94570.586818,60.7,Analytics-ETL,2024-04-06

### **2.SHOW DATASET SHAPE AND SUMMARY BEFORE CLEANING** 

Why we have to make this step ! because by this summary we can noties the changes in the dataset.

In [94]:
#Showing the no.of rows and columns here.
rows,col=department_df.shape
print("Rows:",rows,"Columns:",col)

Rows: 279378 Columns: 46

In [95]:
#Showing the all columns datatypes for the further usage.
department_df.dtypes

dept_analytics_id                object
date                             object
year                              int64
month                             int64
quarter                           int64
day_of_week                      object
is_weekend                         bool
hospital_id                      object
hospital_name                    object
department_id                    object
department_name                  object
department_type                  object
floor_number                      int64
is_24x7                            bool
established_year                  int64
department_head_name             object
total_beds                        int64
occupied_beds_count               int64
bed_occupancy_rate_pct          float64
target_occupancy_rate_pct       float64
patients_admitted_count         float64
patients_discharged_count       float64
readmission_count               float64
readmission_rate_pct            float64
target_readmission_rate_pct     float64
mortality_count                 float64
mortality_rate_pct              float64
avg_length_of_stay_days         float64
target_avg_los_days             float64
avg_treatment_time_hours        float64
transfer_events_count           float64
bed_turnaround_time_hours       float64
nurses_on_duty                    int64
doctors_on_duty                   int64
base_nurses_per_shift             int64
base_doctors_per_shift            int64
staff_to_patient_ratio          float64
equipment_downtime_hours        float64
avg_patient_age                 float64
avg_satisfaction_score          float64
total_billing_usd               float64
avg_cost_per_patient_usd         object
monthly_budget_allocated_usd    float64
department_efficiency_score     float64
record_source_system             object
last_updated_timestamp           object
dtype: object

In [96]:
#The Statistical information of all the numarical datatpye columns.
department_df.describe()

,year,month,quarter,floor_number,established_year,total_beds,occupied_beds_count,bed_occupancy_rate_pct,target_occupancy_rate_pct,patients_admitted_count,patients_discharged_count,readmission_count,readmission_rate_pct,target_readmission_rate_pct,mortality_count,mortality_rate_pct,avg_length_of_stay_days,target_avg_los_days,avg_treatment_time_hours,transfer_events_count,bed_turnaround_time_hours,nurses_on_duty,doctors_on_duty,base_nurses_per_shift,base_doctors_per_shift,staff_to_patient_ratio,equipment_downtime_hours,avg_patient_age,avg_satisfaction_score,total_billing_usd,monthly_budget_allocated_usd,department_efficiency_score
count,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,201160.000000,279378.000000,279378.000000,201160.000000,200354.000000,279378.000000,230851.000000,279378.000000,275196.000000,279378.000000,279378.000000,279378.000000,279378.000000,273796.000000,279378.000000,191696.000000,163077.000000,2.011600e+05,279378.000000,279378.000000
mean,2023.001124,6.524429,2.508991,4.633887,2007.925767,37.654898,25.696859,68.364934,79.161461,1.290127,1.280913,0.627401,48.579906,9.828761,0.038128,2.968904,5.525193,4.554804,67.700022,3.547455,3.205720,7.675189,3.285749,7.952355,3.246827,0.407892,0.487064,47.804439,3.302785,1.339227e+04,343359.075299,39.516986
std,1.413963,3.448838,1.117097,2.246228,5.887694,10.956475,8.037421,8.383797,5.512084,1.148369,1.143471,0.849600,43.717585,2.527332,0.196996,14.337176,26.854656,1.163628,129.728836,1.964595,1.380251,3.473324,1.488461,3.151065,1.326329,2.627178,1.641722,24.457123,1.614606,4.320950e+04,170382.859066,30.315793
min,2021.000000,1.000000,1.000000,1.000000,1998.000000,17.000000,8.000000,39.130000,70.071818,0.000000,0.000000,0.000000,0.000000,6.037037,0.000000,0.000000,-2.000000,2.507822,-5.000000,0.000000,0.200000,1.000000,1.000000,3.000000,1.000000,-1.000000,0.000000,-3.000000,1.000000,-3.000000e+02,84140.072226,0.000000
25%,2022.000000,4.000000,2.000000,3.000000,2003.000000,28.000000,19.000000,63.040000,73.918392,0.000000,0.000000,0.000000,0.000000,7.576509,0.000000,0.000000,2.500000,3.538150,30.750000,2.000000,2.260000,5.000000,2.000000,5.000000,2.000000,0.180000,0.120000,30.000000,2.000000,4.667770e+03,201499.687068,0.000000
50%,2023.000000,7.000000,3.000000,5.000000,2008.000000,37.000000,25.000000,68.000000,79.822052,1.000000,1.000000,0.000000,50.000000,9.628098,0.000000,0.000000,4.000000,4.573767,53.925000,3.000000,3.200000,8.000000,3.000000,8.000000,3.000000,0.310000,0.280000,47.500000,3.000000,9.255960e+03,321713.097207,49.800000
75%,2024.000000,10.000000,4.000000,7.000000,2013.000000,47.000000,32.000000,73.080000,83.784981,2.000000,2.000000,1.000000,100.000000,12.252064,0.000000,0.000000,6.000000,5.722883,83.748125,5.000000,4.140000,10.000000,4.000000,11.000000,4.000000,0.450000,0.560000,65.000000,4.000000,1.619375e+04,497841.592501,67.800000
max,2025.000000,12.000000,4.000000,8.000000,2018.000000,58.000000,81.000000,141.180000,87.924438,9.000000,9.000000,9.000000,100.000000,13.878048,3.000000,100.000000,999.000000,6.363187,5000.000000,17.000000,9.890000,15.000000,6.000000,13.000000,5.000000,99.000000,39.970000,250.000000,10.000000,2.013979e+06,649065.156914,93.100000

In [97]:
#It will Describe every column, including numerical and categorical columns and other supported dtypes as well
#So for the categorical values it will return COUNT,UNIQUE,TOP,FREQUENCY.
department_df.describe(include='all')

,dept_analytics_id,date,year,month,quarter,day_of_week,is_weekend,hospital_id,hospital_name,department_id,department_name,department_type,floor_number,is_24x7,established_year,department_head_name,total_beds,occupied_beds_count,bed_occupancy_rate_pct,target_occupancy_rate_pct,patients_admitted_count,patients_discharged_count,readmission_count,readmission_rate_pct,target_readmission_rate_pct,mortality_count,mortality_rate_pct,avg_length_of_stay_days,target_avg_los_days,avg_treatment_time_hours,transfer_events_count,bed_turnaround_time_hours,nurses_on_duty,doctors_on_duty,base_nurses_per_shift,base_doctors_per_shift,staff_to_patient_ratio,equipment_downtime_hours,avg_patient_age,avg_satisfaction_score,total_billing_usd,avg_cost_per_patient_usd,monthly_budget_allocated_usd,department_efficiency_score,record_source_system,last_updated_timestamp
count,279378,279378,279378.000000,279378.000000,279378.000000,279378,279378,279378,279378,279378,279378,279378,279378.000000,279378,279378.000000,273805,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,279378.000000,201160.000000,279378.000000,279378.000000,201160.000000,200354.000000,279378.000000,230851.000000,279378.000000,275196.000000,279378.000000,279378.000000,279378.000000,279378.000000,273796.000000,279378.000000,191696.000000,163077.000000,2.011600e+05,191073,279378.000000,279378.000000,279378,279378
unique,276091,1826,NaN,NaN,NaN,7,2,10,40,15,75,12,NaN,2,NaN,129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167041,NaN,NaN,12,1829
top,DA00063532,2021-06-01,NaN,NaN,NaN,Monday,False,H010,Unity Regional Medical Center,D09,Renal,Non-Surgical,NaN,False,NaN,Dr. Ivan Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,Analytics-ETL,2025-08-29
freq,2,160,NaN,NaN,NaN,39957,199523,27983,27103,18664,3862,162266,NaN,149018,NaN,5487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8035,NaN,NaN,134601,190
mean,NaN,NaN,2023.001124,6.524429,2.508991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.633887,NaN,2007.925767,NaN,37.654898,25.696859,68.364934,79.161461,1.290127,1.280913,0.627401,48.579906,9.828761,0.038128,2.968904,5.525193,4.554804,67.700022,3.547455,3.205720,7.675189,3.285749,7.952355,3.246827,0.407892,0.487064,47.804439,3.302785,1.339227e+04,NaN,343359.075299,39.516986,NaN,NaN
std,NaN,NaN,1.413963,3.448838,1.117097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.246228,NaN,5.887694,NaN,10.956475,8.037421,8.383797,5.512084,1.148369,1.143471,0.849600,43.717585,2.527332,0.196996,14.337176,26.854656,1.163628,129.728836,1.964595,1.380251,3.473324,1.488461,3.151065,1.326329,2.627178,1.641722,24.457123,1.614606,4.320950e+04,NaN,170382.859066,30.315793,NaN,NaN
min,NaN,NaN,2021.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1998.000000,NaN,17.000000,8.000000,39.130000,70.071818,0.000000,0.000000,0.000000,0.000000,6.037037,0.000000,0.000000,-2.000000,2.507822,-5.000000,0.000000,0.200000,1.000000,1.000000,3.000000,1.000000,-1.000000,0.000000,-3.000000,1.000000,-3.000000e+02,NaN,84140.072226,0.000000,NaN,NaN
25%,NaN,NaN,2022.000000,4.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,2003.000000,NaN,28.000000,19.000000,63.040000,73.918392,0.000000,0.000000,0.000000,0.000000,7.576509,0.000000,0.000000,2.500000,3.538150,30.750000,2.000000,2.260000,5.000000,2.000000,5.000000,2.000000,0.180000,0.120000,30.000000,2.000000,4.667770e+03,NaN,201499.687068,0.000000,NaN,NaN
50%,NaN,NaN,2023.000000,7.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,2008.000000,NaN,37.000000,25.000000,68.000000,79.822052,1.000000,1.000000,0.000000,50.000000,9.628098,0.000000,0.000000,4.000000,4.573767,53.925000,3.000000,3.200000,8.000000,3.000000,8.000000,3.000000,0.310000,0.280000,47.500000,3.000000,9.255960e+03,NaN,321713.097207,49.800000,NaN,NaN
75%,NaN,NaN,2024.000000,10.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,2013.000000,NaN,47.000000,32.000000,73.080000,83.784981,2.000000,2.000000,1.000000,100.000000,12.252064,0.000000,0.000000,6.000000,5.722883,83.748125,5.000000,4.140000,10.000000,4.000000,11.000000,4.000000,0.450000,0.560000,65.000000,4.000000,1.619375e+04,NaN,497841.592501,67.800000,NaN,NaN
max,NaN,NaN,2025.000000,12.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,2018.000000,NaN,58.000000,81.000000,141.180000,87.924438,9.000000,9.000000,9.000000,100.000000,13.878048,3.000000,100.000000,999.000000,6.363187,5000.000000,17.000000,9.890000,15.000000,6.000000,13.000000,5.000000,99.000000,39.970000,250.000000,10.000000,2.013979e+06,NaN,649065.156914,93.100000,NaN,NaN

In [98]:
#Detailed view of Duplicates by the column wise count.
for col in department_df.columns:
    print(f"\n{col}:")
    print(department_df[col].duplicated().sum())

dept_analytics_id:
3287

date:
277552

year:
279373

month:
279366

quarter:
279374

day_of_week:
279371

is_weekend:
279376

hospital_id:
279368

hospital_name:
279338

department_id:
279363

department_name:
279303

department_type:
279366

floor_number:
279370

is_24x7:
279376

established_year:
279357

department_head_name:
279248

total_beds:
279340

occupied_beds_count:
279305

bed_occupancy_rate_pct:
278564

target_occupancy_rate_pct:
279228

patients_admitted_count:
279368

patients_discharged_count:
279368

readmission_count:
279368

readmission_rate_pct:
279352

target_readmission_rate_pct:
279228

mortality_count:
279374

mortality_rate_pct:
279365

avg_length_of_stay_days:
279076

target_avg_los_days:
279228

avg_treatment_time_hours:
205324

transfer_events_count:
279360

bed_turnaround_time_hours:
278548

nurses_on_duty:
279363

doctors_on_duty:
279372

base_nurses_per_shift:
279367

base_doctors_per_shift:
279373

staff_to_patient_ratio:
279260

equipment_downtime_hours:
278311

avg_patient_age:
278231

avg_satisfaction_score:
279286

total_billing_usd:
97622

avg_cost_per_patient_usd:
112336

monthly_budget_allocated_usd:
279228

department_efficiency_score:
278470

record_source_system:
279366

last_updated_timestamp:
277549

In [99]:
#Here we only showing the columns  which have null values not all the columns.
Null_values_cols=department_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

department_head_name           5573
readmission_rate_pct          78218
mortality_rate_pct            78218
avg_length_of_stay_days       79024
avg_treatment_time_hours      48527
bed_turnaround_time_hours      4182
staff_to_patient_ratio         5582
avg_patient_age               87682
avg_satisfaction_score       116301
total_billing_usd             78218
avg_cost_per_patient_usd      88305
dtype: int64

#### **-->For docu & Extra dates removed**

In [100]:
#Here we finding out how much percentage the null values we have ( miss value percentage % )
missing_values=department_df.isnull().sum()
miss_pct=(missing_values[missing_values > 0].sum() / department_df.size )*100
round(miss_pct,2)

5.21

In [101]:
#Here we finding out the over column wise percentage average.
avg_col=(missing_values[missing_values > 0] / len(department_df)) * 100
print("column wise missing value % avg:",round(avg_col.mean(),2))

column wise missing value % avg: 21.8

In [102]:
#Here we finding out the date converage 
max_date=max(department_df['date'])
min_date=min(department_df['date'])
print("The date coverage :",max_date," - ",min_date)

The date coverage : 2025-12-31  -  2021-01-01

### **3.CLEAN UP PROCESS BY DUPLICATE REMOVEL AND NULL VALUE FILLING OR REMOVEL.**

Here we will remove the duplicates first and then we will fill the null values presented columns eaither by statistical values, or we can eliminate themn completely.

#### **-->Work on Duplicates**

In [103]:
#Before removing duplicate values we cheching why does the duplication happened whether by different columns values under dept_analytics_id or repeated data.
department_df[department_df['dept_analytics_id'].duplicated(keep=False)].sort_values('dept_analytics_id') # keep =False will give all the dulicate occurences

,dept_analytics_id,date,year,month,quarter,day_of_week,is_weekend,hospital_id,hospital_name,department_id,department_name,department_type,floor_number,is_24x7,established_year,department_head_name,total_beds,occupied_beds_count,bed_occupancy_rate_pct,target_occupancy_rate_pct,patients_admitted_count,patients_discharged_count,readmission_count,readmission_rate_pct,target_readmission_rate_pct,mortality_count,mortality_rate_pct,avg_length_of_stay_days,target_avg_los_days,avg_treatment_time_hours,transfer_events_count,bed_turnaround_time_hours,nurses_on_duty,doctors_on_duty,base_nurses_per_shift,base_doctors_per_shift,staff_to_patient_ratio,equipment_downtime_hours,avg_patient_age,avg_satisfaction_score,total_billing_usd,avg_cost_per_patient_usd,monthly_budget_allocated_usd,department_efficiency_score,record_source_system,last_updated_timestamp
190216,DA00000118,2021-04-28,2021,4,2,Wednesday,False,H001,St. Mary General Hospital,D01,CARDIOLOGY,Non-Surgical,6,True,2004,Dr. Liam Ali,28,21,75.00,87.924438,2.0,2.0,0.0,0.00,6.629804,0.0,0.0,4.000000,3.068927,57.287500,5.0,3.54,10,4,11,5,0.48,0.24,36.0,4.5,7353.58,3676.79,183069.573807,64.7,Analytics-ETL,2021-05-02
65177,DA00000118,2021-04-28,2021,4,2,Wednesday,False,H001,St. Mary General Hospital,D01,CARDIOLOGY,Non-Surgical,6,True,2004,Dr. Liam Ali,28,21,75.00,87.924438,2.0,2.0,0.0,0.00,6.629804,0.0,0.0,4.000000,3.068927,57.287500,5.0,3.54,10,4,11,5,0.48,0.24,36.0,4.5,7353.58,3676.79,183069.573807,64.7,Analytics-ETL,2021-05-02
3485,DA00000167,2021-06-16,2021,6,2,Wednesday,False,H001,St. Mary General Hospital,D01,Cardiology Dept,Non-Surgical,6,True,2004,Dr. Liam Ali,28,21,75.00,87.924438,0.0,0.0,0.0,NaN,6.629804,0.0,NaN,NaN,3.068927,45.270000,1.0,5.57,9,4,11,5,0.43,0.35,NaN,NaN,NaN,NaN,183069.573807,72.7,Manual Aggregation,2021-06-17
45062,DA00000167,2021-06-16,2021,6,2,Wednesday,False,H001,St. Mary General Hospital,D01,Cardiology Dept,Non-Surgical,6,True,2004,Dr. Liam Ali,28,21,75.00,87.924438,0.0,0.0,0.0,NaN,6.629804,0.0,NaN,NaN,3.068927,45.270000,1.0,5.57,9,4,11,5,0.43,0.35,NaN,NaN,NaN,NaN,183069.573807,72.7,Manual Aggregation,2021-06-17
30668,DA00000508,2022-05-23,2022,5,2,Monday,False,H001,St. Mary General Hospital,D01,cardiology,Non-Surgical,6,True,2004,Dr. Liam Ali,28,18,64.29,87.924438,0.0,2.0,0.0,NaN,6.629804,0.0,NaN,NaN,3.068927,NaN,0.0,3.93,11,4,11,5,0.61,0.05,NaN,NaN,NaN,NaN,183069.573807,69.4,BI-Warehouse,2022-05-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177062,DA00273624,2025-03-30,2025,3,1,Sunday,True,H010,Evercare Medical Center,D15,urology,Surgical,5,False,2002,Dr. Elena Costa,54,37,68.52,76.798699,0.0,3.0,0.0,NaN,9.828074,0.0,NaN,NaN,5.828615,NaN,0.0,5.55,2,2,5,2,0.05,0.68,NaN,NaN,NaN,NaN,308989.949257,75.6,Analytics-ETL,2025-04-02
236008,DA00273844,2025-11-05,2025,11,4,Wednesday,False,H010,Evercare Medical Center,D15,Urology Dept,Surgical,5,False,2002,Dr. Elena Costa,54,42,77.78,76.798699,3.0,3.0,2.0,66.67,9.828074,0.0,0.0,2.333333,5.828615,15.375000,6.0,1.33,4,2,5,2,0.10,0.28,73.0,5.0,14610.77,4870.26,308989.949257,2.8,Manual Aggregation,2025-11-08
231955,DA00273844,2025-11-05,2025,11,4,Wednesday,False,H010,Evercare Medical Center,D15,Urology Dept,Surgical,5,False,2002,Dr. Elena Costa,54,42,77.78,76.798699,3.0,3.0,2.0,66.67,9.828074,0.0,0.0,2.333333,5.828615,15.375000,6.0,1.33,4,2,5,2,0.10,0.28,73.0,5.0,14610.77,4870.26,308989.949257,2.8,Manual Aggregation,2025-11-08
276415,DA00273890,2025-12-21,2025,12,4,Sunday,True,H010,Evercare Medical Center,D15,Urology,Surgical,5,False,2002,Dr. Elena Costa,54,39,72.22,76.798699,2.0,6.0,1.0,50.00,9.828074,0.0,0.0,6.500000,5.828615,109.183333,9.0,4.34,5,1,5,2,0.13,0.79,80.5,NaN,22637.72,11318.86,308989.949257,20.9,Manual Aggregation,2025-12-24
101003,DA00273890,2025-12-21,2025,12,4,Sunday,True,H010,Evercare Medical Center,D15,Urology,Surgical,5,False,2002,Dr. Elena Costa,54,39,72.22,76.798699,2.0,6.0,1.0,50.00,9.828074,0.0,0.0,6.500000,5.828615,109.183333,9.0,4.34,5,1,5,2,0.13,0.79,80.5,NaN,22637.72,11318.86,308989.949257,20.9,Manual Aggregation,2025-12-24

In [104]:
#Removing the dulicate values by the dept_analytics_id.
department_df.drop_duplicates(subset=['dept_analytics_id'], keep='first',inplace=True) #keep='first' will keep the duplicate of first row remove remaining 
                                                                              #subset=['dept_analytics_id'] will used to decide the whether a row is duplicate or not.

In [105]:
#Checking whether the column dept_analytics_id have any duplicate values.
department_df['dept_analytics_id'].duplicated().sum()

0

#### **-->WORKING ON NULL VALUES**

In [106]:
#1.Depatment head name will be filled with the frequent item.
department_df['department_head_name']=department_df['department_head_name'].fillna('Dr. Ivan Smith')

In [107]:
#2.Here readmission rate pct will first recalculate for the pre precaution.
department_df['readmission_rate_pct']=(department_df['readmission_count'] / department_df['patients_admitted_count'] )*100
department_df['readmission_rate_pct']=department_df['readmission_rate_pct'].fillna(0) #here the when division happened with both zeros a nan will come so we filled with 0.

In [108]:
#3.Here we filling the mortality rate pct Na values with the zeros because it was Nulled by the both zeros division.
department_df['mortality_rate_pct']=department_df['mortality_rate_pct'].fillna(0)

In [109]:
#4.Here avg length of stay days will be filled with the avg (mean).
department_df['avg_length_of_stay_days']=department_df['avg_length_of_stay_days'].fillna(5.53)

In [110]:
#5.Here avg avg_treatment_time_hours will be filled with the avg (mean).
department_df['avg_treatment_time_hours']=department_df['avg_treatment_time_hours'].fillna(67.68)

In [111]:
#6.Here avg bed_turnaround_time_hours will be filled with the avg (mean).
department_df['bed_turnaround_time_hours']=department_df['bed_turnaround_time_hours'].fillna(3.20)

In [112]:
#7.Here we filling the staff to patient ration by the recalculating again.
department_df['staff_to_patient_ratio']=department_df['nurses_on_duty'] / department_df['occupied_beds_count']

In [113]:
#8.Here the avg patient age for every department NA values will  be filled with the avg(mean).
department_df['avg_patient_age']=department_df['avg_patient_age'].fillna(47.8)

In [114]:
#9.Here the avg_satisfaction_score for every department NA values will  be filled with the avg(mean).
department_df['avg_satisfaction_score']=department_df['avg_satisfaction_score'].fillna(3.30)

In [115]:
#10.Here total billing usd NA will be filled with the avg(mean).
department_df['total_billing_usd']=department_df['total_billing_usd'].fillna(department_df['total_billing_usd'].mean())

In [116]:
#11.Here total billing usd NA will be filled with the avg(mean).
department_df['avg_cost_per_patient_usd'] = (
    department_df['avg_cost_per_patient_usd']
    .str.replace('$', '', regex=False) #we replacing the dollar with empty space.
    .str.replace(',', '', regex=False) #we replaing the , with empty space.
    .str.replace('USD','',regex=False) #we replaing the USD with empty space.
    .astype(float)
)
department_df['avg_cost_per_patient_usd']=department_df['avg_cost_per_patient_usd'].fillna(department_df['avg_cost_per_patient_usd'].mean())

#### **--> Checking does there exist NAN values**

In [117]:
#Here we only showing the columns  which have null values not all the columns.
Null_values_cols=department_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

Series([], dtype: int64)

### **4.CORRECTION : COL_NAMES, COL_VALUES , DTYPES ETC.**

#### **-->Standardize ID's**

In [118]:
#Here we capitalizing the all the first letter of the column names.
department_df.columns = department_df.columns.str.capitalize()
department_df.columns

Index(['Dept_analytics_id', 'Date', 'Year', 'Month', 'Quarter', 'Day_of_week',
       'Is_weekend', 'Hospital_id', 'Hospital_name', 'Department_id',
       'Department_name', 'Department_type', 'Floor_number', 'Is_24x7',
       'Established_year', 'Department_head_name', 'Total_beds',
       'Occupied_beds_count', 'Bed_occupancy_rate_pct',
       'Target_occupancy_rate_pct', 'Patients_admitted_count',
       'Patients_discharged_count', 'Readmission_count',
       'Readmission_rate_pct', 'Target_readmission_rate_pct',
       'Mortality_count', 'Mortality_rate_pct', 'Avg_length_of_stay_days',
       'Target_avg_los_days', 'Avg_treatment_time_hours',
       'Transfer_events_count', 'Bed_turnaround_time_hours', 'Nurses_on_duty',
       'Doctors_on_duty', 'Base_nurses_per_shift', 'Base_doctors_per_shift',
       'Staff_to_patient_ratio', 'Equipment_downtime_hours', 'Avg_patient_age',
       'Avg_satisfaction_score', 'Total_billing_usd',
       'Avg_cost_per_patient_usd', 'Monthly_budget_allocated_usd',
       'Department_efficiency_score', 'Record_source_system',
       'Last_updated_timestamp'],
      dtype='object')

In [119]:
#Here we Change the numarical ID's into the Strings.
cols=department_df.columns
for ids in cols:
    if ids.endswith('id'):
        department_df[ids]=department_df[ids].astype('string')

#### **-->Standardize Departments**

In [120]:
#Here we assigning the values to the department according to the department ids.
Dept_id_mapping={
    'D01':'Cardiology',
    'D02':'Orthopedics',
    'D03':'Neurology',
    'D04':'Oncology',
    'D05':'Pediatrics',
    'D06':'General surgery',
    'D07':'Emergency',
    'D08':'Obstetrics & gynecology',
    'D09':'Nephrology',
    'D10':'Pulmonology',
    'D11':'Gastroenterology',
    'D12':'Psychiatry',
    'D13':'Icu',
    'D14':'General medicine',
    'D15':'Urology'    
}

department_df['Department_name']=department_df['Department_id'].map(Dept_id_mapping)

#### **--> Standardize Text**

In [121]:
#Here we are performing removing the leading and trailing spaces from the values in the columns.
column_names=['Hospital_name',
              'Department_type',
              'Record_source_system']

for col in column_names:
    department_df[col]=department_df[col].str.strip()

In [122]:
#Here we are performing the capitalize to remove any deplicate values.
column_names_cap=['Hospital_name',
                  'Department_type',
                  'Record_source_system']

for col in column_names_cap:
    department_df[col]=department_df[col].str.capitalize()

In [123]:
#Here we are rounding the floating values into 2 decimals.
column_names_float=['Target_occupancy_rate_pct',
                    	'Readmission_rate_pct',
                        'Target_readmission_rate_pct',
                        'Mortality_rate_pct',
                        'Target_avg_los_days',
                        'Avg_treatment_time_hours',
                        'Staff_to_patient_ratio',
                        'Avg_satisfaction_score',
                        'Total_billing_usd',
                        'Avg_cost_per_patient_usd',
                        'Monthly_budget_allocated_usd']

for col in column_names_float:
    department_df[col]=round(department_df[col],2)

In [124]:
#Here we are converting the dtype of needed columns into integer.
col_name_int=['Patients_admitted_count',
              'Patients_discharged_count',
              'Readmission_count',
              'Mortality_count',
              'Transfer_events_count',
              'Avg_length_of_stay_days',
              'Avg_patient_age']

for col in col_name_int:
    department_df[col]=department_df[col].astype(int)

#### **-->Date standardization**

In [125]:
#here if there are any columns which related date containing different formats we making them as the date related dtype columns
dates_related_cols=['Date','Last_updated_timestamp']
for col in dates_related_cols:
    department_df[col]=pd.to_datetime(department_df[col])

#### **-->Outlier validation**

In [126]:
department_df.describe(include='all')

,Dept_analytics_id,Date,Year,Month,Quarter,Day_of_week,Is_weekend,Hospital_id,Hospital_name,Department_id,Department_name,Department_type,Floor_number,Is_24x7,Established_year,Department_head_name,Total_beds,Occupied_beds_count,Bed_occupancy_rate_pct,Target_occupancy_rate_pct,Patients_admitted_count,Patients_discharged_count,Readmission_count,Readmission_rate_pct,Target_readmission_rate_pct,Mortality_count,Mortality_rate_pct,Avg_length_of_stay_days,Target_avg_los_days,Avg_treatment_time_hours,Transfer_events_count,Bed_turnaround_time_hours,Nurses_on_duty,Doctors_on_duty,Base_nurses_per_shift,Base_doctors_per_shift,Staff_to_patient_ratio,Equipment_downtime_hours,Avg_patient_age,Avg_satisfaction_score,Total_billing_usd,Avg_cost_per_patient_usd,Monthly_budget_allocated_usd,Department_efficiency_score,Record_source_system,Last_updated_timestamp
count,276091,276091,276091.000000,276091.000000,276091.000000,276091,276091,276091,276091,276091,276091,276091,276091.000000,276091,276091.000000,276091,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,276091.000000,2.760910e+05,276091.000000,276091.000000,276091.000000,276091,276091
unique,276091,NaN,NaN,NaN,NaN,7,2,10,10,15,15,3,NaN,2,NaN,129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
top,DA00116235,NaN,NaN,NaN,NaN,Monday,False,H010,Evercare medical center,D10,Pulmonology,Non-surgical,NaN,False,NaN,Dr. Ivan Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Analytics-etl,NaN
freq,1,NaN,NaN,NaN,NaN,39485,197177,27636,27636,18423,18423,165672,NaN,147260,NaN,10924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137562,NaN
mean,NaN,2023-07-02 12:58:44.490114048,2023.000605,6.524146,2.508981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.633237,NaN,2007.925597,NaN,37.654407,25.697513,68.367321,79.162276,1.290578,1.280802,0.627608,34.989944,9.828911,0.038158,2.138479,5.279118,4.554792,67.687986,3.547703,3.205532,7.675998,3.285413,7.952715,3.246527,0.339279,0.486765,47.455154,3.302035,1.339673e+04,8362.736627,343437.933425,39.508844,NaN,2023-07-05 00:58:58.415957248
min,NaN,2021-01-01 00:00:00,2021.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1998.000000,NaN,17.000000,8.000000,39.130000,70.070000,0.000000,0.000000,0.000000,0.000000,6.040000,0.000000,0.000000,-2.000000,2.510000,-5.000000,0.000000,0.200000,1.000000,1.000000,3.000000,1.000000,0.010000,0.000000,-3.000000,1.000000,-3.000000e+02,-500.000000,84140.070000,0.000000,NaN,2021-01-02 00:00:00
25%,NaN,2022-04-02 00:00:00,2022.000000,4.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,2003.000000,NaN,28.000000,19.000000,63.040000,73.920000,0.000000,0.000000,0.000000,0.000000,7.580000,0.000000,0.000000,3.000000,3.540000,36.090000,2.000000,2.270000,5.000000,2.000000,5.000000,2.000000,0.180000,0.120000,39.000000,3.000000,6.341185e+03,4505.660000,201499.690000,0.000000,NaN,2022-04-05 00:00:00
50%,NaN,2023-07-03 00:00:00,2023.000000,7.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,2008.000000,NaN,37.000000,25.000000,68.000000,79.990000,1.000000,1.000000,0.000000,0.000000,9.630000,0.000000,0.000000,5.000000,4.570000,65.480000,3.000000,3.200000,8.000000,3.000000,8.000000,3.000000,0.310000,0.280000,47.000000,3.300000,1.339673e+04,8320.780000,321713.100000,49.800000,NaN,2023-07-05 00:00:00
75%,NaN,2024-10-01 00:00:00,2024.000000,10.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,2013.000000,NaN,47.000000,32.000000,73.080000,83.780000,2.000000,2.000000,1.000000,100.000000,12.250000,0.000000,0.000000,5.000000,5.720000,75.120000,5.000000,4.120000,10.000000,4.000000,11.000000,4.000000,0.450000,0.560000,56.000000,3.500000,1.339673e+04,8362.740000,497841.590000,67.800000,NaN,2024-10-04 00:00:00
max,NaN,2025-12-31 00:00:00,2025.000000,12.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,2018.000000,NaN,58.000000,81.000000,141.180000,87.920000,9.000000,9.000000,9.000000,100.000000,13.880000,3.000000,100.000000,999.000000,6.360000,5000.000000,17.000000,9.890000,15.000000,6.000000,13.000000,5.000000,1.750000,39.970000,250.000000,10.000000,2.013979e+06,999999.990000,649065.160000,93.100000,NaN,2026-01-04 00:00:00
std,NaN,NaN,1.413974,3.448882,1.117156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.246373,NaN,5.887711,NaN,10.956192,8.038134,8.385032,5.512797,1.148596,1.143370,0.849817,43.039243,2.527921,0.197057,12.239516,22.868192,1.163565,117.814783,1.964721,1.369696,3.472992,1.488599,3.150624,1.326333,0.209922,1.639898,20.265262,1.233985,3.672755e+04,33177.094403,170407.854711,30.317747,NaN,NaN

In [127]:
#Here we just converted the negative outlier into the positive onces 
department_df['Avg_length_of_stay_days']=abs(department_df['Avg_length_of_stay_days'])
department_df['Avg_treatment_time_hours']=abs(department_df['Avg_treatment_time_hours'])
department_df['Avg_patient_age']=abs(department_df['Avg_patient_age'])

In [128]:
#Here once again we showing the all the dtypes of the columns.
department_df.dtypes

Dept_analytics_id               string[python]
Date                            datetime64[ns]
Year                                     int64
Month                                    int64
Quarter                                  int64
Day_of_week                             object
Is_weekend                                bool
Hospital_id                     string[python]
Hospital_name                           object
Department_id                   string[python]
Department_name                         object
Department_type                         object
Floor_number                             int64
Is_24x7                                   bool
Established_year                         int64
Department_head_name                    object
Total_beds                               int64
Occupied_beds_count                      int64
Bed_occupancy_rate_pct                 float64
Target_occupancy_rate_pct              float64
Patients_admitted_count                  int32
Patients_discharged_count                int32
Readmission_count                        int32
Readmission_rate_pct                   float64
Target_readmission_rate_pct            float64
Mortality_count                          int32
Mortality_rate_pct                     float64
Avg_length_of_stay_days                  int32
Target_avg_los_days                    float64
Avg_treatment_time_hours               float64
Transfer_events_count                    int32
Bed_turnaround_time_hours              float64
Nurses_on_duty                           int64
Doctors_on_duty                          int64
Base_nurses_per_shift                    int64
Base_doctors_per_shift                   int64
Staff_to_patient_ratio                 float64
Equipment_downtime_hours               float64
Avg_patient_age                          int32
Avg_satisfaction_score                 float64
Total_billing_usd                      float64
Avg_cost_per_patient_usd               float64
Monthly_budget_allocated_usd           float64
Department_efficiency_score            float64
Record_source_system                    object
Last_updated_timestamp          datetime64[ns]
dtype: object

In [129]:
department_df.head(2)

,Dept_analytics_id,Date,Year,Month,Quarter,Day_of_week,Is_weekend,Hospital_id,Hospital_name,Department_id,Department_name,Department_type,Floor_number,Is_24x7,Established_year,Department_head_name,Total_beds,Occupied_beds_count,Bed_occupancy_rate_pct,Target_occupancy_rate_pct,Patients_admitted_count,Patients_discharged_count,Readmission_count,Readmission_rate_pct,Target_readmission_rate_pct,Mortality_count,Mortality_rate_pct,Avg_length_of_stay_days,Target_avg_los_days,Avg_treatment_time_hours,Transfer_events_count,Bed_turnaround_time_hours,Nurses_on_duty,Doctors_on_duty,Base_nurses_per_shift,Base_doctors_per_shift,Staff_to_patient_ratio,Equipment_downtime_hours,Avg_patient_age,Avg_satisfaction_score,Total_billing_usd,Avg_cost_per_patient_usd,Monthly_budget_allocated_usd,Department_efficiency_score,Record_source_system,Last_updated_timestamp
0,DA00116235,2024-04-11,2024,4,2,Thursday,False,H005,Metro city hospital,D04,Oncology,Non-surgical,4,False,2001,Dr. Carlos Ivanov,46,36,78.26,86.68,2,4,2,100.0,11.57,0,0.0,4,3.87,58.76,4,0.78,5,3,7,4,0.14,0.14,49,2.0,4131.26,2065.63,175431.27,0.0,Analytics-etl,2024-04-12
1,DA00092491,2024-04-05,2024,4,2,Friday,False,H004,Sunrise health institute,D06,General surgery,Surgical,4,False,2007,Dr. Elena Brown,30,22,73.33,84.65,1,1,0,0.0,9.41,0,0.0,5,5.69,49.20,4,3.23,5,5,3,5,0.23,0.16,19,5.0,6515.81,6515.81,94570.59,60.7,Analytics-etl,2024-04-06

In [130]:
#Here we finding out the int and float related columns by specifying 'number' parameter.
numeric_columns = department_df.select_dtypes(  #Here the select dtypes is pandas fun which can return the specified dtype columns
    include='number'
).columns.tolist() # here we get the pandas dataframe so we converting that into python list.

for col in numeric_columns:
    print(col)

Year
Month
Quarter
Floor_number
Established_year
Total_beds
Occupied_beds_count
Bed_occupancy_rate_pct
Target_occupancy_rate_pct
Patients_admitted_count
Patients_discharged_count
Readmission_count
Readmission_rate_pct
Target_readmission_rate_pct
Mortality_count
Mortality_rate_pct
Avg_length_of_stay_days
Target_avg_los_days
Avg_treatment_time_hours
Transfer_events_count
Bed_turnaround_time_hours
Nurses_on_duty
Doctors_on_duty
Base_nurses_per_shift
Base_doctors_per_shift
Staff_to_patient_ratio
Equipment_downtime_hours
Avg_patient_age
Avg_satisfaction_score
Total_billing_usd
Avg_cost_per_patient_usd
Monthly_budget_allocated_usd
Department_efficiency_score

In [133]:
#Here we are removing the extra date rows that are more then the hospital admissions dates.
department_df = department_df[department_df['Date'] != '2025-12-31']

### **5.CONVERTING THE CURRENT DATAFRAME INTO THE CSV FILE**

As per the requriement we are going to make this dataframe into the csv gile for the analysisi.

In [135]:
#Here we converted the current department_df into csv file.
department_df.to_csv(
    r"C:\powerbipro\Health_Domain_pro_Infosys\MedTrack_DV\Data\Processed_data\Department_cleaned.csv",
    index=False
)

### **6.SUMMARY OF THE DATASET**


1. **Dataset Overview**
   We first provide an overview of the dataset, including its structure, number of rows and columns, and the key information available in the dataset.

2. **Pre-Cleaning Data Summary**
   Next, we analyze the dataset **before cleaning** by performing statistical analysis and examining the data **column-wise** to identify missing values, duplicates, data types, inconsistent values, and other data-quality issues.

3. **Data Cleaning**
   The dataset is then cleaned by **removing duplicate records** and handling missing values. Numerical columns are filled using the **mean value**, while missing values in categorical columns are replaced with the **most frequently occurring value (mode)**.

4. **Column and Data-Type Standardization**
   After that, we standardize the dataset by **correcting column names**, removing **repeated/multi-value entries**, and converting columns to their appropriate **data types** to ensure consistency and improve data usability.

5. **Final Dataset Export**
   Finally, the cleaned and standardized dataset is converted and exported into **CSV format**, making it ready for further analysis, visualization, and dashboard development.