### **1.PATIENT FLOW DATASET CLEANING**

Here we will work on the patient flow dataset to clean and make it ready for the data analysis.

In [1]:
#Needed Libraries will be imported here.
import pandas as pd
import numpy as np

In [2]:
#By the file path we are importing the file into the patient_df variable
patient_df=pd.read_csv("C:\\powerbipro\\Health_Domain_pro_Infosys\\MedTrack_DV\\Data\\Raw_data\\patient_flow_dataset.csv")

In [3]:
#Initially Displaying the top and bottom rows.
patient_df

,movement_id,admission_id,patient_id,hospital_id,hospital_name,movement_sequence,movement_type,from_department_id,from_department_name,current_department_id,...,movement_date,movement_year,movement_month,day_of_week,hour_of_day,shift,is_peak_hour,duration_in_department_hours,ward_occupancy_pct_at_time,length_of_stay_days
0,M00730171,A0039282,P099607,H001,St. Mary General Hospital,2,Discharge,D07,emergency medicine,D07,...,2022-02-10,2022,2,Thursday,0,Night (12-8am),False,NaN,96.0,1.0
1,M00019289,A0065850,P068540,H005,Metro City Hospital,3,ICU Transfer,D10,Pulmonology,D02,...,2025-02-26,2025,2,Wednesday,19,Evening (4-8pm),True,28.03,36.0,2.0
2,M00529311,A0263194,P019456,H001,St. Mary General Hospital,3,Discharge,D09,Nephrology,D09,...,2023-04-26,2023,4,Wednesday,0,Night (12-8am),False,NaN,65.0,1.0
3,M00348842,A0158166,P187670,H004,Sunrise Health Institute,3,Ward Transfer,D13,ICU,D07,...,2022-07-08,2022,7,Friday,22,Night (8pm-12am),False,1.45,99.0,1.0
4,M00352066,A0231590,P023406,H006,Green Valley Hospital,1,Admission,NaN,NaN,D11,...,2022-08-25,2022,8,Thursday,0,Night (12-8am),False,72.00,80.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972537,M00250961,A0334530,P088953,H005,Metro City Hospital,1,Admission,NaN,NaN,D02,...,2022-09-25,2022,9,Sunday,0,Night (12-8am),False,120.00,83.0,5.0
972538,M00741347,A0007563,P113022,H001,St. Mary General Hospital,1,Admission,NaN,NaN,D02,...,2025-03-20,2025,3,Thursday,0,Night (12-8am),False,98.32,69.0,5.0
972539,M00847757,A0020648,P133497,H006,Green Valley Hospital,2,Ward Transfer,D01,cardiology,D13,...,2024-11-26,2024,11,Tuesday,4,NIGHT (12-8AM),False,23.05,83.0,4.0
972540,M00656292,A0038549,P042423,H007,Unity Regional Medical Center,3,ward transfer,D07,Emergency Medicine,D01,...,2022-06-12,2022,6,Sunday,3,Night (12-8am),False,12.37,70.0,7.0
972541,M00821185,A0337091,P225328,H004,Sunrise Health Institute,1,Admission,NaN,NaN,D08,...,2021-06-17,2021,6,Thursday,0,Night (12-8am),False,95.67,86.0,12.0

In [4]:
#By the default available functions we are fully displaying the columns ( as per the need we can also display rows as well).
pd.set_option('display.max_columns',39)
patient_df.head(2)

,movement_id,admission_id,patient_id,hospital_id,hospital_name,movement_sequence,movement_type,from_department_id,from_department_name,current_department_id,current_department_name,from_location,to_location,bed_id,bed_type,mode_of_transport,authorized_by_staff,reason_for_movement,movement_datetime,movement_date,movement_year,movement_month,day_of_week,hour_of_day,shift,is_peak_hour,duration_in_department_hours,ward_occupancy_pct_at_time,length_of_stay_days
0,M00730171,A0039282,P099607,H001,St. Mary General Hospital,2,Discharge,D07,emergency medicine,D07,emergency medicine,emergency medicine,Home,B1306,HDU,Ambulance,"Rosa Okafor, RN",Bed availability,2022-02-10 00:00,2022-02-10,2022,2,Thursday,0,Night (12-8am),False,NaN,96.0,1.0
1,M00019289,A0065850,P068540,H005,Metro City Hospital,3,ICU Transfer,D10,Pulmonology,D02,Orthopedics,Pulmonology,Orthopedics,B1438,ICU,Stretcher,"Rosa Novak, RN",PATIENT REQUEST,2025-02-26 19:58,2025-02-26,2025,2,Wednesday,19,Evening (4-8pm),True,28.03,36.0,2.0

### **2.SHOW DATASET SHAPE AND SUMMARY BEFORE CLEANING** 

Why we have to make this step ! because by this summary we can noties the changes in the dataset.

In [5]:
#Showing the no.of rows and columns here.
rows,col=patient_df.shape
print("Rows:",rows,"Columns:",col)

Rows: 972542 Columns: 29

In [6]:
#Showing the all columns datatypes for the further usage.
patient_df.dtypes

movement_id                      object
admission_id                     object
patient_id                       object
hospital_id                      object
hospital_name                    object
movement_sequence                 int64
movement_type                    object
from_department_id               object
from_department_name             object
current_department_id            object
current_department_name          object
from_location                    object
to_location                      object
bed_id                           object
bed_type                         object
mode_of_transport                object
authorized_by_staff              object
reason_for_movement              object
movement_datetime                object
movement_date                    object
movement_year                     int64
movement_month                    int64
day_of_week                      object
hour_of_day                       int64
shift                            object
is_peak_hour                       bool
duration_in_department_hours    float64
ward_occupancy_pct_at_time      float64
length_of_stay_days             float64
dtype: object

In [7]:
#The Statistical information of all the numarical datatpye columns.
patient_df.describe()

,movement_sequence,movement_year,movement_month,hour_of_day,duration_in_department_hours,ward_occupancy_pct_at_time,length_of_stay_days
count,972542.000000,972542.000000,972542.000000,972542.000000,602727.000000,953123.000000,972542.000000
mean,2.015949,2023.003876,6.524042,2.923876,67.307004,67.428988,4.674705
std,1.034068,1.415649,3.450105,6.093318,171.435810,19.326950,4.003127
min,1.000000,2021.000000,1.000000,0.000000,-5.000000,-10.000000,0.000000
25%,1.000000,2022.000000,4.000000,0.000000,18.000000,51.000000,2.000000
50%,2.000000,2023.000000,7.000000,0.000000,48.000000,67.000000,4.000000
75%,3.000000,2024.000000,10.000000,1.000000,96.000000,84.000000,6.000000
max,5.000000,2026.000000,12.000000,23.000000,5000.000000,150.000000,60.000000

In [8]:
#It will Describe every column, including numerical and categorical columns and other supported dtypes as well
#So for the categorical values it will return COUNT,UNIQUE,TOP,FREQUENCY.
patient_df.describe(include='all')

,movement_id,admission_id,patient_id,hospital_id,hospital_name,movement_sequence,movement_type,from_department_id,from_department_name,current_department_id,current_department_name,from_location,to_location,bed_id,bed_type,mode_of_transport,authorized_by_staff,reason_for_movement,movement_datetime,movement_date,movement_year,movement_month,day_of_week,hour_of_day,shift,is_peak_hour,duration_in_department_hours,ward_occupancy_pct_at_time,length_of_stay_days
count,972542,972542,972542,972542,972542,972542.000000,972542,612033,605875,972542,972542,972542,972542,953071,972542,943356,948258,914140,972542,972542,972542.000000,972542.000000,972542,972542.000000,972542,972542,602727.000000,953123.000000,972542.000000
unique,961100,353500,179814,10,40,NaN,9,15,246,15,246,99,80,2000,5,20,200,40,238421,1845,NaN,NaN,7,NaN,16,2,NaN,NaN,NaN
top,M00744438,A0245316,P115780,H007,Unity Regional Medical Center,NaN,Admission,D09,ICU,D09,ICU,Self,Home,B0379,General Ward,Ambulatory,"Ann Diaz, RN",Routine discharge,2024-07-05 00:00,2024-03-22,NaN,NaN,Friday,NaN,Night (12-8am),False,NaN,NaN,NaN
freq,2,8,29,98651,94838,NaN,360509,41163,21022,65366,33953,58017,298817,589,425070,319884,4945,88782,467,636,NaN,NaN,139415,NaN,782289,910875,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,2.015949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.003876,6.524042,NaN,2.923876,NaN,NaN,67.307004,67.428988,4.674705
std,NaN,NaN,NaN,NaN,NaN,1.034068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.415649,3.450105,NaN,6.093318,NaN,NaN,171.435810,19.326950,4.003127
min,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,1.000000,NaN,0.000000,NaN,NaN,-5.000000,-10.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,4.000000,NaN,0.000000,NaN,NaN,18.000000,51.000000,2.000000
50%,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.000000,7.000000,NaN,0.000000,NaN,NaN,48.000000,67.000000,4.000000
75%,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.000000,10.000000,NaN,1.000000,NaN,NaN,96.000000,84.000000,6.000000
max,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026.000000,12.000000,NaN,23.000000,NaN,NaN,5000.000000,150.000000,60.000000

In [9]:
#Detailed view of Duplicates by the column wise count.
for col in patient_df.columns:
    print(f"\n{col}:")
    print(patient_df[col].duplicated().sum())

movement_id:
11442

admission_id:
619042

patient_id:
792728

hospital_id:
972532

hospital_name:
972502

movement_sequence:
972537

movement_type:
972533

from_department_id:
972526

from_department_name:
972295

current_department_id:
972527

current_department_name:
972296

from_location:
972443

to_location:
972462

bed_id:
970541

bed_type:
972537

mode_of_transport:
972521

authorized_by_staff:
972341

reason_for_movement:
972501

movement_datetime:
734121

movement_date:
970697

movement_year:
972536

movement_month:
972530

day_of_week:
972535

hour_of_day:
972518

shift:
972526

is_peak_hour:
972540

duration_in_department_hours:
956344

ward_occupancy_pct_at_time:
972472

length_of_stay_days:
972506

In [10]:
#Here we only showing the columns  which have null values not all the columns.
Null_values_cols=patient_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

from_department_id              360509
from_department_name            366667
bed_id                           19471
mode_of_transport                29186
authorized_by_staff              24284
reason_for_movement              58402
duration_in_department_hours    369815
ward_occupancy_pct_at_time       19419
dtype: int64

In [11]:
#Here we finding out how much percentage the null values we have ( miss value percentage % )
missing_values=patient_df.isnull().sum()
miss_pct=(missing_values[missing_values > 0].sum() / patient_df.size )*100
round(miss_pct,2)

4.42

In [12]:
#Here we finding out the over column wise percentage average.
avg_col=(missing_values[missing_values > 0] / len(patient_df)) * 100
print("column wise missing value % avg:",round(avg_col.mean(),2))

column wise missing value % avg: 16.04

In [13]:
#Here we finding out the date converage 
max_date=max(patient_df['movement_date'])
min_date=min(patient_df['movement_date'])
print("The date coverage :",max_date," - ",min_date)

The date coverage : 2026-01-19  -  2021-01-01

### **3.CLEAN UP PROCESS BY DUPLICATE REMOVEL AND NULL VALUE FILLING OR REMOVEL.**

Here we will remove the duplicates first and then we will fill the null values presented columns eaither by statistical values, or we can eliminate themn completely.

#### **-->Work on Duplicates**

In [14]:
#Before removing duplicate values we cheching why does the duplication happened whether by different columns values under movement id or repeated data.
patient_df[patient_df['movement_id'].duplicated(keep=False)].sort_values('movement_id') # keep =False will give all the dulicate occurences

,movement_id,admission_id,patient_id,hospital_id,hospital_name,movement_sequence,movement_type,from_department_id,from_department_name,current_department_id,current_department_name,from_location,to_location,bed_id,bed_type,mode_of_transport,authorized_by_staff,reason_for_movement,movement_datetime,movement_date,movement_year,movement_month,day_of_week,hour_of_day,shift,is_peak_hour,duration_in_department_hours,ward_occupancy_pct_at_time,length_of_stay_days
436876,M00000044,A0087476,P180195,H007,Unity Regional Medical Center,1,Admission,NaN,NaN,D03,Neurology,Physician Referral,Neurology,B1351,General Ward,Wheelchair,"Ann Kaur, RN",Routine discharge,2024-07-16 00:00,2024-07-16,2024,7,Tuesday,0,Night (12-8am),False,240.00,48.0,10.0
953569,M00000044,A0087476,P180195,H007,Unity Regional Medical Center,1,Admission,NaN,NaN,D03,Neurology,Physician Referral,Neurology,B1351,General Ward,Wheelchair,"Ann Kaur, RN",Routine discharge,2024-07-16 00:00,2024-07-16,2024,7,Tuesday,0,Night (12-8am),False,240.00,48.0,10.0
196334,M00000084,A0060967,P154197,H010,Evercare Medical Center,3,ward transfer,D13,ICU,D07,Emergency Medicine,ICU,Emergency Medicine,B0929,General Ward,Stretcher,"Nora Silva, RN",ICU step-down,2022-03-02 00:49,2022-03-02,2022,3,Wednesday,0,NIGHT (12-8AM),False,119.18,53.0,11.0
739811,M00000084,A0060967,P154197,H010,Evercare Medical Center,3,ward transfer,D13,ICU,D07,Emergency Medicine,ICU,Emergency Medicine,B0929,General Ward,Stretcher,"Nora Silva, RN",ICU step-down,2022-03-02 00:49,2022-03-02,2022,3,Wednesday,0,NIGHT (12-8AM),False,119.18,53.0,11.0
11640,M00000109,A0315568,P141437,H010,Evercare Medical Center,2,Department Transfer,D04,Oncology Dept,D09,Nephrology,Oncology Dept,Nephrology,B0213,ICU,Bed Transport,"Nora Adeyemi, RN",Bed availability,2022-11-04 06:24,2022-11-04,2022,11,Friday,6,Night (12-8am),False,7.87,99.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668745,M00952950,A0222722,P090211,H007,Unity Regional Medical Center,1,Admission,NaN,NaN,D07,Emergency Dept,Physician Referral,Emergency Dept,B1231,General Ward,Ambulatory,"Deepak Ivanov, RN",NaN,2021-07-23 00:00,2021-07-23,2021,7,Friday,0,Night (12-8am),False,120.00,48.0,5.0
288308,M00952961,A0210893,P219321,H010,Evercare Medical Center,2,Discharge,D02,Orthopedics,D02,Orthopedics,Orthopedics,Home,B1529,General Ward,Ambulatory,"Ann Ivanov, RN",Scheduled procedure,2023-03-09 00:00,2023-03-09,2023,3,Thursday,0,Night (12-8am),False,NaN,95.0,5.0
781649,M00952961,A0210893,P219321,H010,Evercare Medical Center,2,Discharge,D02,Orthopedics,D02,Orthopedics,Orthopedics,Home,B1529,General Ward,Ambulatory,"Ann Ivanov, RN",Scheduled procedure,2023-03-09 00:00,2023-03-09,2023,3,Thursday,0,Night (12-8am),False,NaN,95.0,5.0
748894,M00953402,A0203606,P199051,H002,Lakeview Medical Center,2,Discharge,D02,Orthopedic,D02,Orthopedic,Orthopedic,Home,B0885,Private Room,Wheelchair,"Deepak Reed, RN",Specialist care required,2025-10-02 00:00,2025-10-02,2025,10,Thursday,0,Night (12-8am),False,NaN,75.0,5.0
305741,M00953402,A0203606,P199051,H002,Lakeview Medical Center,2,Discharge,D02,Orthopedic,D02,Orthopedic,Orthopedic,Home,B0885,Private Room,Wheelchair,"Deepak Reed, RN",Specialist care required,2025-10-02 00:00,2025-10-02,2025,10,Thursday,0,Night (12-8am),False,NaN,75.0,5.0

In [15]:
#Removing the dulicate values by the movement_id.
patient_df.drop_duplicates(subset=['movement_id'], keep='first',inplace=True) #keep='first' will keep the duplicate of first row remove remaining 
                                                                              #subset=['movement_id'] will used to decide the whether a row is duplicate or not.

In [16]:
#Checking whether the new hospital_df_dup_rev column movement_id have any duplicate values.
patient_df['movement_id'].duplicated().sum()

0

#### **-->WORKING ON NULL VALUES**

In [17]:
#1.We filled the from department id by using the randow choice function from the numpy.
col = 'from_department_id'

unique_values = patient_df[col].dropna().unique()

mask = patient_df[col].isna()

patient_df.loc[mask, col] = np.random.choice(
    unique_values,
    size=mask.sum()   # here we are tell to the np how may values it has to be generate.here mask.sum()values
)

In [18]:
#2.the Na department_name will be replaced by the represented value of the department id.
#why we have to do like this beacuse when we randomly fill the NA values it might one dept id will get verient dept names so thats why,
#we took deptnames mannually and filled according to the dept id.
patient_df['from_department_name']=patient_df['from_department_name'].str.strip()
patient_df['from_department_name']=patient_df['from_department_name'].str.capitalize()
#patient_df['from_department_name'].unique()
patient_df['from_department_id']=patient_df['from_department_id'].astype('string')

In [19]:
#Here we displaying all the department names for mannual collection
#pd.set_option('display.max_rows',71)
patient_df[['from_department_id','from_department_name']].drop_duplicates().sort_values(by='from_department_id')

    from_department_id from_department_name
12                 D01           Cardiology
21                 D01                  NaN
131                D01      Cardiology dept
64                 D01               Cardio
377                D02           Orthopedic
..                 ...                  ...
40                 D14        Gen. medicine
187                D15                  Uro
17                 D15              Urology
408                D15         Urology dept
110                D15                  NaN

[71 rows x 2 columns]

In [20]:
Dept_id_mapping={
    'D01':'Cardiology',
    'D02':'Orthopedics',
    'D03':'Neurology',
    'D04':'Oncology',
    'D05':'Pediatrics',
    'D06':'General surgery',
    'D07':'Emergency',
    'D08':'Obstetrics & gynecology',
    'D09':'Nephrology',
    'D10':'Pulmonology',
    'D11':'Gastroenterology',
    'D12':'Psychiatry',
    'D13':'Icu',
    'D14':'General medicine',
    'D15':'Urology'    
}

In [21]:
#By the mapping function we get he proper value of the key and assigned to the from department names.
patient_df['from_department_name'] = patient_df['from_department_id'].map(Dept_id_mapping)
patient_df['from_department_name'].unique() # again checking here for any repeated values.

array(['Emergency', 'Pulmonology', 'Nephrology', 'Icu',
       'Gastroenterology', 'Obstetrics & gynecology', 'General surgery',
       'General medicine', 'Neurology', 'Cardiology', 'Pediatrics',
       'Orthopedics', 'Oncology', 'Urology', 'Psychiatry'], dtype=object)

In [22]:
#3.Here bed id Na values will be replaced by the frequent id.
patient_df['bed_id']=patient_df['bed_id'].fillna('B0379')

In [23]:
#4.Here mode of transport of a patient NA values will be filled by the frequently repeated value.
patient_df['mode_of_transport']=patient_df['mode_of_transport'].fillna('Ambulatory')

In [24]:
#5.Here authorized by staff NA value will be replaced by the frequently repeated value.
patient_df['authorized_by_staff']=patient_df['authorized_by_staff'].fillna('Ann Diaz, RN')

In [25]:
#6.Here reason for movement column Na value will be filled with the frequent value.
patient_df['reason_for_movement']=patient_df['reason_for_movement'].fillna('Routine discharge')

In [26]:
#7.Here duration in department hours will be Na will be filled with the avg.
patient_df['duration_in_department_hours']=patient_df['duration_in_department_hours'].fillna(67.307004)

In [27]:
#8.here ward occupancy pct at time column Na values will be replaced with the avg.
patient_df['ward_occupancy_pct_at_time']=patient_df['ward_occupancy_pct_at_time'].fillna(67.428988)

#### **--> Checking does there exist NAN values**

In [28]:
#Here we only showing the columns  which have null values not all the columns.
Null_values_cols=patient_df.isnull().sum() #series datasturcture will be returned here
Null_values_cols[Null_values_cols > 0]

Series([], dtype: int64)

### **4.CORRECTION : COL_NAMES, COL_VALUES , DTYPES ETC.**

#### **-->Standardize ID's**

In [29]:
#Here we capitalizing the all the first letter of the column names.
patient_df.columns = patient_df.columns.str.capitalize()
patient_df.columns

Index(['Movement_id', 'Admission_id', 'Patient_id', 'Hospital_id',
       'Hospital_name', 'Movement_sequence', 'Movement_type',
       'From_department_id', 'From_department_name', 'Current_department_id',
       'Current_department_name', 'From_location', 'To_location', 'Bed_id',
       'Bed_type', 'Mode_of_transport', 'Authorized_by_staff',
       'Reason_for_movement', 'Movement_datetime', 'Movement_date',
       'Movement_year', 'Movement_month', 'Day_of_week', 'Hour_of_day',
       'Shift', 'Is_peak_hour', 'Duration_in_department_hours',
       'Ward_occupancy_pct_at_time', 'Length_of_stay_days'],
      dtype='object')

In [30]:
#Here we Change the numarical ID's into the Strings.
cols=patient_df.columns
for ids in cols:
    if ids.endswith('id'):
        patient_df[ids]=patient_df[ids].astype('string')

#### **--> Standardize Text**

In [31]:
#Here we removed any leading and trial spaces of the values in the columns.
patient_df['From_location']=patient_df['From_location'].str.strip()
patient_df['Mode_of_transport']=patient_df['Mode_of_transport'].str.strip()
patient_df['Reason_for_movement']=patient_df['Reason_for_movement'].str.strip()
patient_df['Shift']=patient_df['Shift'].str.strip()

In [32]:
#Here we capitalize the values in column to reduce the different value repetation. 
patient_df['Hospital_name']=patient_df['Hospital_name'].str.capitalize()
patient_df['Movement_type']=patient_df['Movement_type'].str.capitalize()
patient_df['From_location']=patient_df['From_location'].str.capitalize()
patient_df['To_location']=patient_df['To_location'].str.capitalize()
patient_df['Mode_of_transport']=patient_df['Mode_of_transport'].str.capitalize()
patient_df['Reason_for_movement']=patient_df['Reason_for_movement'].str.capitalize()
patient_df['Shift']=patient_df['Shift'].str.capitalize()

#### **-->Standardize Departments**

In [33]:
#Here we assigning the correct department names to the current dept name based on the current dept id.
patient_df['Current_department_name'] = patient_df['Current_department_id'].map(Dept_id_mapping)

#### **-->Date standardization**

In [34]:
#here if there are any columns which related date containing different formats we making them as the date related dtype columns
dates_related_cols=['Movement_datetime','Movement_date']
for col in dates_related_cols:
    patient_df[col]=pd.to_datetime(patient_df[col])

#### **-->Outlier validation**

In [35]:
patient_df.describe(include='all')

,Movement_id,Admission_id,Patient_id,Hospital_id,Hospital_name,Movement_sequence,Movement_type,From_department_id,From_department_name,Current_department_id,Current_department_name,From_location,To_location,Bed_id,Bed_type,Mode_of_transport,Authorized_by_staff,Reason_for_movement,Movement_datetime,Movement_date,Movement_year,Movement_month,Day_of_week,Hour_of_day,Shift,Is_peak_hour,Duration_in_department_hours,Ward_occupancy_pct_at_time,Length_of_stay_days
count,961100,961100,961100,961100,961100,961100.000000,961100,961100,961100,961100,961100,961100,961100,961100,961100,961100,961100,961100,961100,961100,961100.000000,961100.000000,961100,961100.000000,961100,961100,961100.000000,961100.000000,961100.000000
unique,961100,353500,179814,10,20,NaN,8,15,15,15,15,62,69,2000,5,5,200,10,NaN,NaN,NaN,NaN,7,NaN,4,2,NaN,NaN,NaN
top,M00730171,A0302281,P115780,H007,Unity regional medical center,NaN,Admission,D11,Gastroenterology,D09,Nephrology,Referral,Home,B0379,General Ward,Ambulatory,"Ann Diaz, RN",Routine discharge,NaN,NaN,NaN,NaN,Friday,NaN,Night (12-8am),False,NaN,NaN,NaN
freq,1,7,29,97553,96633,NaN,356295,64552,64552,64635,64635,59635,295277,19813,419991,355468,28902,148276,NaN,NaN,NaN,NaN,137735,NaN,798695,900108,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,2.015859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-03 19:28:45.850774784,2023-07-03 16:25:41.433774080,2023.003781,6.524108,NaN,2.924182,NaN,NaN,67.315975,67.429517,4.674354
min,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-01 00:00:00,2021-01-01 00:00:00,2021.000000,1.000000,NaN,0.000000,NaN,NaN,-5.000000,-10.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-04-02 00:00:00,2022-04-02 00:00:00,2022.000000,4.000000,NaN,0.000000,NaN,NaN,31.680000,51.000000,2.000000
50%,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-05 00:00:00,2023-07-05 00:00:00,2023.000000,7.000000,NaN,0.000000,NaN,NaN,67.307004,67.428988,4.000000
75%,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-01 23:38:45,2024-10-01 00:00:00,2024.000000,10.000000,NaN,1.000000,NaN,NaN,67.307004,84.000000,6.000000
max,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-19 00:00:00,2026-01-19 00:00:00,2026.000000,12.000000,NaN,23.000000,NaN,NaN,5000.000000,150.000000,60.000000
std,NaN,NaN,NaN,NaN,NaN,1.034013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.415690,3.450360,NaN,6.093374,NaN,NaN,135.103292,19.132602,4.001064

In [36]:
#Here we droping the column Duration in department hours from the dataframe because this column is useless when we have lenght of stay column we have.
patient_df.drop(columns="Duration_in_department_hours",inplace=True)

In [37]:
#here we change the negative values into postive by the abs () function.
patient_df['Ward_occupancy_pct_at_time']=abs(patient_df['Ward_occupancy_pct_at_time'])

In [38]:
#columns dtype for once again 
patient_df.dtypes

Movement_id                   string[python]
Admission_id                  string[python]
Patient_id                    string[python]
Hospital_id                   string[python]
Hospital_name                         object
Movement_sequence                      int64
Movement_type                         object
From_department_id            string[python]
From_department_name                  object
Current_department_id         string[python]
Current_department_name               object
From_location                         object
To_location                           object
Bed_id                        string[python]
Bed_type                              object
Mode_of_transport                     object
Authorized_by_staff                   object
Reason_for_movement                   object
Movement_datetime             datetime64[ns]
Movement_date                 datetime64[ns]
Movement_year                          int64
Movement_month                         int64
Day_of_week                           object
Hour_of_day                            int64
Shift                                 object
Is_peak_hour                            bool
Ward_occupancy_pct_at_time           float64
Length_of_stay_days                  float64
dtype: object

#### **-->Know NUMBER columns**

In [39]:
#Here we finding out the int and float related columns by specifying 'number' parameter.
numeric_columns = patient_df.select_dtypes(  #Here the select dtypes is pandas fun which can return the specified dtype columns
    include='number'
).columns.tolist() # here we get the pandas dataframe so we converting that into python list.

for col in numeric_columns:
    print(col)

Movement_sequence
Movement_year
Movement_month
Hour_of_day
Ward_occupancy_pct_at_time
Length_of_stay_days

In [40]:
patient_df.head(5)

,Movement_id,Admission_id,Patient_id,Hospital_id,Hospital_name,Movement_sequence,Movement_type,From_department_id,From_department_name,Current_department_id,Current_department_name,From_location,To_location,Bed_id,Bed_type,Mode_of_transport,Authorized_by_staff,Reason_for_movement,Movement_datetime,Movement_date,Movement_year,Movement_month,Day_of_week,Hour_of_day,Shift,Is_peak_hour,Ward_occupancy_pct_at_time,Length_of_stay_days
0,M00730171,A0039282,P099607,H001,St. mary general hospital,2,Discharge,D07,Emergency,D07,Emergency,Emergency medicine,Home,B1306,HDU,Ambulance,"Rosa Okafor, RN",Bed availability,2022-02-10 00:00:00,2022-02-10,2022,2,Thursday,0,Night (12-8am),False,96.0,1.0
1,M00019289,A0065850,P068540,H005,Metro city hospital,3,Icu transfer,D10,Pulmonology,D02,Orthopedics,Pulmonology,Orthopedics,B1438,ICU,Stretcher,"Rosa Novak, RN",Patient request,2025-02-26 19:58:00,2025-02-26,2025,2,Wednesday,19,Evening (4-8pm),True,36.0,2.0
2,M00529311,A0263194,P019456,H001,St. mary general hospital,3,Discharge,D09,Nephrology,D09,Nephrology,Nephrology,Unknown (absconded),B1426,Semi-Private,Wheelchair,"Priya Okafor, RN",Patient request,2023-04-26 00:00:00,2023-04-26,2023,4,Wednesday,0,Night (12-8am),False,65.0,1.0
3,M00348842,A0158166,P187670,H004,Sunrise health institute,3,Ward transfer,D13,Icu,D07,Emergency,Icu,Emergency medicine,B0548,Private Room,Ambulance,"Nora Silva, RN",Infection control isolation,2022-07-08 22:33:00,2022-07-08,2022,7,Friday,22,Night (8pm-12am),False,99.0,1.0
4,M00352066,A0231590,P023406,H006,Green valley hospital,1,Admission,D11,Gastroenterology,D11,Gastroenterology,Self,Gi dept,B1633,General Ward,Ambulatory,"Priya Silva, RN",Routine discharge,2022-08-25 00:00:00,2022-08-25,2022,8,Thursday,0,Night (12-8am),False,80.0,3.0

In [41]:
#Here we are removing the extra date rows that are more then the hospital admissions dates.
patient_df = patient_df[patient_df['Movement_date'] <= '2025-12-30']

In [42]:
patient_df['Movement_date'].max()

Timestamp('2025-12-30 00:00:00')

### **5.CONVERTING THE CURRENT DATAFRAME INTO THE CSV FILE**

As per the requriement we are going to make this dataframe into the csv gile for the analysisi.

In [43]:
#Here we converted the current patient_df into csv file.
patient_df.to_csv(
    r"C:\powerbipro\Health_Domain_pro_Infosys\MedTrack_DV\Data\Processed_data\Patient_cleaned.csv",
    index=False
)

### **6.SUMMARY OF THE DATASET**


1. **Dataset Overview**
   We first provide an overview of the dataset, including its structure, number of rows and columns, and the key information available in the dataset.

2. **Pre-Cleaning Data Summary**
   Next, we analyze the dataset **before cleaning** by performing statistical analysis and examining the data **column-wise** to identify missing values, duplicates, data types, inconsistent values, and other data-quality issues.

3. **Data Cleaning**
   The dataset is then cleaned by **removing duplicate records** and handling missing values. Numerical columns are filled using the **mean value**, while missing values in categorical columns are replaced with the **most frequently occurring value (mode)**.

4. **Column and Data-Type Standardization**
   After that, we standardize the dataset by **correcting column names**, removing **repeated/multi-value entries**, and converting columns to their appropriate **data types** to ensure consistency and improve data usability.

5. **Final Dataset Export**
   Finally, the cleaned and standardized dataset is converted and exported into **CSV format**, making it ready for further analysis, visualization, and dashboard development.